// GENERATED by tools/build.mjs from elements/tab-panel/: do not edit.
import { PkElement, define } from '../../js/element.js';
const behaviour = Base => class extends Base {
    connected() { if (!this.slot) this.slot = 'panel'; this.updated(); }
    updated() { this.aria({ role: 'tabpanel' }); }
};
export default define(class extends behaviour(PkElement) {
    static tag = "pk-tab-panel";
    static props = {"value":{"type":"string","default":"","reflect":true},"selected":{"type":"boolean","default":false,"reflect":true}};
    static delegatesFocus = false;
    static formAssociated = false;
    static template = "<slot></slot>";
    static css = ":host { display: block; }\n:host(:not([selected])) { display: none; }\n:host(:focus-visible) { outline: var(--focus-ring); outline-offset: 2px; }\n";
});
