// Family B: Blazor and Razor only (design section 2.6, issue #518 A-9). Every other family's markup rules
// (S, D, T, A, P) already run against .razor/.cshtml through the same tolerant HTML/Razor tokenizer
// (core/tools/strict/scanners/html.mjs, design section 4.1/7: `@* *@` comments, `@{ }`/`@( )` blocks and bare
// `@expr` are skipped as opaque, `Pk*`/uppercase tags are recognised as components) - there is no separate
// "Razor scanner" module to write, the scanner already is Razor-aware. B rules exist only where the Blazor
// surface differs from plain HTML/JS: a raw tag versus a `Pk*` component, a component's own parameters, and a
// couple of Razor-only syntax shapes (`@onclick`, `MarkupString`, `@page`/`@inherits`).
//
// Data source: BLAZOR_COMPONENTS (core/tools/audit/hints.mjs, generated by core/tools/audit/data.mjs from
// blazor/mappings/*.json - the same file scripts/generate-blazor.mjs and the Blazor skill already read), keyed
// by pk-* tag with `{ component, params[] }`. B3 also needs the reverse lookup (component name -> params),
// built once below from the same table - no new source, per the design's "nothing is invented" rule (section 3).
import { scanHtml } from '../../strict/scanners/html.mjs';
import { hitsForEach, hitAt, fileIs, RAZOR_EXTENSIONS } from '../util.mjs';
import { TAG_HINTS, BLAZOR_COMPONENTS } from '../hints.mjs';

const isRazor = file => fileIs(file, RAZOR_EXTENSIONS);
const isPkComponent = name => /^Pk[A-Z]/.test(name);

// Reverse of BLAZOR_COMPONENTS (tag -> {component, params}): component name -> params[], for B3.
const PARAMS_BY_COMPONENT = Object.fromEntries(Object.values(BLAZOR_COMPONENTS).map(v => [v.component, v.params]));

// Framework/passthrough attributes every component accepts regardless of its own params (design section 7:
// "an attribute that is not a parameter ... is put on the element as it is"), so B3 never flags these as an
// unknown parameter - B2 already covers Class/Style on its own.
const PASSTHROUGH_ATTRS = new Set(['Class', 'Style', 'id', 'key']);

// B5's JS-interop hint table (D7's counterpart, design section 2.6): an IJSRuntime call by string name that
// duplicates behaviour a component already owns. Hand-written like D7's own API_PATTERNS (core/tools/audit/
// hints.mjs) - these are Blazor interop call names, not an element catalogue field.
const INTEROP_HINTS = [
    { re: /\.showModal\b/, api: 'showModal', element: 'pk-dialog' },
    { re: /\bclipboard\.writeText\b/, api: 'clipboard.writeText', element: 'pk-copy-button (or the clipboard-aware element you are copying from)' },
    { re: /\b(disableBodyScroll|enableBodyScroll|scrollLock|lockScroll)\b/, api: 'a manual scroll lock', element: 'pk-dialog/pk-drawer (they already lock body scroll while open)' },
];

export const B_RULES = [
    {
        id: 'B1',
        category: 'B',
        detects: 'a raw HTML tag in a .razor/.cshtml file where a Pk* component exists (D1\'s Razor counterpart)',
        severity: { normal: 'warn', strict: 'error' },
        docs: 'docs/superpowers/specs/2026-09-28-conformance-audit-cli-design.md#26-family-b-blazor-and-razor-only',
        fixTemplate: 'FIX: {file}:{line} writes <{found}>. PlainKit already ships {component}: use it instead of the raw tag. [B1]',
        applies: isRazor,
        scan(file) {
            const { nodes } = scanHtml(file.text);
            const hits = [];
            for (const node of nodes) {
                if (node.closing || isPkComponent(node.name)) continue;
                const pkTag = TAG_HINTS[node.name.toLowerCase()];
                if (!pkTag) continue;
                const blazor = BLAZOR_COMPONENTS[pkTag];
                const component = blazor ? `<${blazor.component}>` : `<${pkTag}> (no Blazor component generated for it yet)`;
                hits.push({ line: node.line, column: node.column, message: `<${node.name}>`, found: node.name, component });
            }
            return hits;
        },
    },
    {
        id: 'B2',
        category: 'B',
        detects: 'class=/style= on markup, or Class/Style on a Pk* component (S1-S3 counterpart)',
        severity: { normal: 'warn', strict: 'error' },
        docs: 'docs/superpowers/specs/2026-09-28-conformance-audit-cli-design.md#26-family-b-blazor-and-razor-only',
        fixTemplate: 'FIX: {file}:{line} sets {found} on {component}. Use the component\'s own parameters instead of styling it from outside. [B2]',
        applies: isRazor,
        scan(file) {
            const { nodes } = scanHtml(file.text);
            const hits = [];
            for (const node of nodes) {
                if (node.closing || !isPkComponent(node.name)) continue;
                for (const attr of ['Class', 'Style']) {
                    if (node.attrs[attr] === undefined) continue;
                    hits.push({ line: node.line, column: node.column, message: `${attr}=`, found: `${attr}=`, component: `<${node.name}>` });
                }
            }
            return hits;
        },
    },
    {
        id: 'B3',
        category: 'B',
        detects: 'an unknown Pk* component, or an unknown parameter on a known one (typo or removed parameter)',
        severity: { normal: 'error', strict: 'error' },
        docs: 'docs/superpowers/specs/2026-09-28-conformance-audit-cli-design.md#26-family-b-blazor-and-razor-only',
        fixTemplate: 'FIX: {file}:{line} {found}. [B3]',
        applies: isRazor,
        scan(file) {
            const { nodes } = scanHtml(file.text);
            const hits = [];
            for (const node of nodes) {
                if (node.closing || !isPkComponent(node.name)) continue;
                const params = PARAMS_BY_COMPONENT[node.name];
                if (!params) {
                    hits.push({ line: node.line, column: node.column, message: `<${node.name}>`, found: `<${node.name}> is not a known PlainKit component (check the spelling, or it does not exist)` });
                    continue;
                }
                for (const attrName of Object.keys(node.attrs)) {
                    if (PASSTHROUGH_ATTRS.has(attrName) || attrName.startsWith('data-') || attrName.startsWith('aria-')) continue;
                    if (!params.includes(attrName)) {
                        hits.push({ line: node.line, column: node.column, message: `${attrName}=`, found: `<${node.name} ${attrName}=...> - ${attrName} is not a parameter of ${node.name} (check the spelling, or it was removed)` });
                    }
                }
            }
            return hits;
        },
    },
    {
        id: 'B4',
        category: 'B',
        detects: 'a @page component that does not derive from the SDK\'s page base',
        severity: { normal: 'warn', strict: 'warn' },
        docs: 'docs/superpowers/specs/2026-09-28-conformance-audit-cli-design.md#26-family-b-blazor-and-razor-only',
        fixTemplate: 'FIX: {file}:{line} {found}. [B4]',
        applies: isRazor,
        scan(file) {
            if (!/@page\b/.test(file.text)) return [];
            if (/@inherits\s+\S*PageBase\b/.test(file.text)) return [];
            const m = /@page\b[^\r\n]*/.exec(file.text);
            return [hitAt(file.text, m.index, '@page', { found: 'this @page component has no @inherits ...PageBase - the app framework\'s page lifecycle (loading/error/empty states) will not run' })];
        },
    },
    {
        id: 'B5',
        category: 'B',
        detects: 'JS interop for a behaviour a component already owns (a hint, never an error: D7\'s Blazor counterpart)',
        severity: { normal: 'warn', strict: 'warn' },
        docs: 'docs/superpowers/specs/2026-09-28-conformance-audit-cli-design.md#26-family-b-blazor-and-razor-only',
        fixTemplate: 'FIX: {file}:{line} calls IJSRuntime for {api}. {element} already owns this; check whether it covers your case before keeping the interop call. [B5]',
        applies: isRazor,
        scan(file) {
            const hits = [];
            for (const { re, api, element } of INTEROP_HINTS) {
                hits.push(...hitsForEach(file.text, new RegExp(re.source, 'g'), m => hitAt(file.text, m.index, api, { found: api, api, element })));
            }
            return hits;
        },
    },
    {
        id: 'B6',
        category: 'B',
        detects: 'a <script> tag, an inline onclick on a non-component tag, or a MarkupString built from a non-literal value',
        severity: { normal: 'warn', strict: 'error' },
        docs: 'docs/superpowers/specs/2026-09-28-conformance-audit-cli-design.md#26-family-b-blazor-and-razor-only',
        fixTemplate: 'FIX: {file}:{line} {found}. [B6]',
        applies: isRazor,
        scan(file) {
            const { nodes } = scanHtml(file.text);
            const hits = [];
            for (const node of nodes) {
                if (node.closing) continue;
                if (node.name.toLowerCase() === 'script') {
                    hits.push({ line: node.line, column: node.column, message: '<script>', found: '<script> element in Razor markup - use a PlainKit element or its documented API instead of hand-written script' });
                }
                if (!isPkComponent(node.name) && node.attrs.onclick !== undefined) {
                    hits.push({ line: node.line, column: node.column, message: `<${node.name} onclick>`, found: `<${node.name}> has an inline onclick; use @onclick on a real interactive element or compose a pk-* one` });
                }
            }
            hits.push(...hitsForEach(file.text, /new\s+MarkupString\s*\(\s*(?!["'`])([^)]+)\)/g, m => hitAt(file.text, m.index, 'MarkupString', { found: `new MarkupString(${m[1].trim()}) from a non-literal value - unsanitised markup can inject script` })));
            hits.push(...hitsForEach(file.text, /\(MarkupString\)\s*([A-Za-z_][\w.]*)/g, m => hitAt(file.text, m.index, 'MarkupString', { found: `(MarkupString)${m[1]} cast from a non-literal value - unsanitised markup can inject script` })));
            return hits;
        },
    },
];
