// GENERATED by tools/build.mjs from elements/media/: do not edit.
import { PkElement, define } from '../../js/element.js';
const behaviour = Base => class extends Base {
    connected() {
        if (this.$c) return;
        const open = () => { const m = this.slotted().find(e => e.localName === 'img' || e.localName === 'video' || e.localName === 'picture'); const img = m?.localName === 'picture' ? m.querySelector('img') : m; this.emit('pk-open', { src: img?.currentSrc || img?.src || '', alt: img?.alt || '', caption: this.caption }); };
        this.$c = () => { if (this.lightbox) open(); };
        this.$k = e => { if (this.lightbox && (e.key === 'Enter' || e.key === ' ')) { e.preventDefault(); open(); } };
        this.part('box').addEventListener('click', this.$c);
        this.part('box').addEventListener('keydown', this.$k);
        this.watchSlot('caption', () => this.requestUpdate());
    }
    updated() {
        this.part('caption').hidden = !this.caption && this.slotted('caption').length === 0;
        this.style.setProperty('--_r', this.ratio.replace('/', ' / '));
        const box = this.part('box');
        if (this.lightbox) { box.setAttribute('role', 'button'); box.tabIndex = 0; box.setAttribute('aria-label', this.caption ? `Enlarge: ${this.caption}` : 'Enlarge image'); }
        else { box.removeAttribute('role'); box.removeAttribute('tabindex'); box.removeAttribute('aria-label'); }
    }
};
export default define(class extends behaviour(PkElement) {
    static tag = "pk-media";
    static props = {"ratio":{"type":"string","default":"16/9","reflect":false},"fit":{"type":"enum","default":"cover","values":["cover","contain"],"reflect":true},"caption":{"type":"string","default":"","reflect":false},"lightbox":{"type":"boolean","default":false,"reflect":true},"square":{"type":"boolean","default":false,"reflect":true}};
    static delegatesFocus = false;
    static formAssociated = false;
    static template = "<figure part=\"figure\"><div part=\"box\"><slot></slot></div><figcaption part=\"caption\"><slot name=\"caption\">{{caption}}</slot></figcaption></figure>";
    static css = ":host { display: block; }\nfigure { display: grid; gap: var(--space-2); margin: 0; }\n[part=\"box\"] { position: relative; aspect-ratio: var(--_r, 16 / 9); overflow: hidden; border-radius: var(--pk-media-radius, var(--radius-md)); background: var(--color-surface-alt); }\n:host([square]) [part=\"box\"] { border-radius: 0; }\n::slotted(img), ::slotted(video), ::slotted(picture), ::slotted(svg) { position: absolute; inset: 0; inline-size: 100%; block-size: 100%; object-fit: cover; }\n:host([fit=\"contain\"]) ::slotted(img), :host([fit=\"contain\"]) ::slotted(video) { object-fit: contain; }\n:host([lightbox]) [part=\"box\"] { cursor: zoom-in; }\n:host([lightbox]) [part=\"box\"]:focus-visible { outline: var(--focus-ring); outline-offset: 2px; }\n[part=\"caption\"] { color: var(--color-muted); font-size: var(--text-meta); }\n";
});
