// GENERATED by tools/build.mjs from elements/tabs/: do not edit.
import { PkElement, define } from '../../js/element.js';
const ids = { n: 0 };
const behaviour = Base => class extends Base {
    connected() {
        this.watchSlot('tab', () => this.sync()); this.watchSlot('panel', () => this.sync());
        const list = this.part('list');
        if (!this.$k) {
            this.$k = true;
            list.addEventListener('click', e => { const t = e.target.closest?.('pk-tab'); if (t) this.choose(t); });
            list.addEventListener('keydown', e => this.key(e));
            list.addEventListener('scroll', () => this.fade());
            if (typeof ResizeObserver !== 'undefined') new ResizeObserver(() => this.fade()).observe(list);
        }
        this.sync();
    }
    changed(name) { if (name === 'value' || name === 'noneActive') this.sync(); if (name === 'scroll') this.fade(); }
    get tabs() { return this.slotted('tab').filter(t => t.localName === 'pk-tab'); }
    get panels() { return this.slotted('panel').filter(p => p.localName === 'pk-tab-panel'); }
    get shown() { return this.tabs.filter(t => !t.disabled && t.offsetParent !== null); }
    sync() {
        const tabs = this.tabs;
        if (!tabs.length) return;
        if (this.value && !tabs.some(t => t.value === this.value)) this.warnOnce(`value:${this.value}`, `value="${this.value}" matches no <pk-tab value>: falling back to the first enabled tab`, { value: this.value, tabs: tabs.map(t => t.value) });
        if (!this.noneActive && !tabs.some(t => t.value === this.value && !t.disabled)) { const previous = this.value; this.value = (tabs.find(t => !t.disabled) ?? tabs[0]).value; if (this.value !== previous) this.emit('pk-tab-change', { value: this.value, previous }, { cancelable: false }); }
        for (const t of tabs) {
            t.id ||= 'pk-tab-' + (++ids.n);
            const on = !this.noneActive && t.value === this.value;
            t.selected = on; t.tabIndex = on || this.noneActive ? 0 : -1;
            const p = this.panels.find(x => x.value === t.value);
            if (p) { p.id ||= 'pk-panel-' + (++ids.n); t.setAttribute('aria-controls', p.id); p.setAttribute('aria-labelledby', t.id); }
        }
        for (const p of this.panels) { p.selected = !this.noneActive && p.value === this.value; p.tabIndex = p.selected ? 0 : -1; }
        if (this.scroll) this.tabs.find(t => t.selected)?.scrollIntoView({ block: 'nearest', inline: 'nearest' });
        this.fade();
    }
    fade() {
        const l = this.part('list'); if (!l) return;
        const max = l.scrollWidth - l.clientWidth;
        const side = !this.scroll || max <= 1 ? '' : l.scrollLeft <= 1 ? 'end' : l.scrollLeft >= max - 1 ? 'start' : 'both';
        if (side) l.setAttribute('data-fade', side); else l.removeAttribute('data-fade');
    }
    choose(tab, focus = false) {
        if (tab.disabled || (!this.noneActive && tab.value === this.value)) { if (focus) tab.focus(); return; }
        const previous = this.value;
        if (!this.noneActive) this.value = tab.value;
        if (!this.emit('pk-tab-change', { value: tab.value, previous })) { if (!this.noneActive) this.value = previous; return; }
        if (focus) tab.focus();
    }
    key(e) {
        const tabs = this.shown; const i = tabs.indexOf(e.target.closest('pk-tab'));
        if (i < 0) return;
        const to = { ArrowRight: (i + 1) % tabs.length, ArrowLeft: (i - 1 + tabs.length) % tabs.length, Home: 0, End: tabs.length - 1 }[e.key];
        if (to === undefined) return;
        e.preventDefault();
        if (this.activation === 'manual' || this.noneActive) { for (const t of this.tabs) t.tabIndex = t === tabs[to] ? 0 : -1; tabs[to].focus(); } else this.choose(tabs[to], true);
    }
};
export default define(class extends behaviour(PkElement) {
    static tag = "pk-tabs";
    static props = {"value":{"type":"string","default":"","reflect":true},"activation":{"type":"enum","default":"auto","values":["auto","manual"],"reflect":true},"noneActive":{"type":"boolean","default":false,"reflect":true},"scroll":{"type":"boolean","default":false,"reflect":true}};
    static delegatesFocus = false;
    static formAssociated = false;
    static template = "<div part=\"list\" role=\"tablist\"><slot name=\"tab\"></slot><slot name=\"trailing\"></slot></div><div part=\"panels\"><slot name=\"panel\"></slot></div>";
    static css = ":host { display: block; }\n[part=\"list\"] { display: flex; flex-wrap: wrap; align-items: center; gap: var(--space-1); border-bottom: 1px solid var(--color-border); margin-bottom: var(--space-4); }\n:host([scroll]) [part=\"list\"] { flex-wrap: nowrap; overflow-x: auto; overscroll-behavior-x: contain; scroll-snap-type: x proximity; scrollbar-width: none; }\n:host([scroll]) [part=\"list\"]::-webkit-scrollbar { display: none; }\n:host([scroll]) ::slotted(*) { flex: none; white-space: nowrap; scroll-snap-align: start; }\n[part=\"list\"][data-fade=\"end\"] { mask-image: linear-gradient(to right, black calc(100% - 1.75rem), transparent); }\n[part=\"list\"][data-fade=\"start\"] { mask-image: linear-gradient(to right, transparent, black 1.75rem); }\n[part=\"list\"][data-fade=\"both\"] { mask-image: linear-gradient(to right, transparent, black 1.75rem, black calc(100% - 1.75rem), transparent); }\n";
});
