// The on-demand element loader: finds pk-* tags that are not defined yet, imports only the modules they need (each cacheable on its own)
// and, with observe, does the same for elements added later. The registry maps a tag to its module, relative to the registry file:
//   elements/registry.js  { "pk-button": "./button/button.element.js", ... }   (generated by tools/build.mjs; dist/ has its own)

import { createLogger, isLogEnabled } from './log.js';

const log = createLogger('loader');
const loaded = new Map();
const reported = new Set();
const observed = new WeakSet();

// Which modules to import: the pk-* tags in `tags` that the registry knows and `have` does not hold yet. Pure.
export function planLoad(tags, registry, have = new Set()) {
    const out = [];
    for (const tag of new Set(tags)) if (tag.startsWith('pk-') && registry[tag] && !have.has(tag)) out.push({ tag, path: registry[tag] });
    return out;
}

const tagsIn = root => [...(root.matches?.(':not(:defined)') ? [root] : []), ...root.querySelectorAll(':not(:defined)')].map(e => e.localName).filter(t => t.startsWith('pk-'));

async function registryOf(url) { return (await import(url)).default; }

export async function loadElements(root = document, { registry = new URL('../elements/registry.js', import.meta.url).href } = {}) {
    const tags = (() => { try { return tagsIn(root); } catch (error) { log.debug('could not scan for pk-* tags', error); return []; } })();
    if (!tags.length) return [];
    let reg;
    try { reg = await registryOf(registry); } catch (error) { log.error(`could not load the element registry from ${registry}`, error); return []; }
    // A pk-* tag the registry does not know is usually a typo: say so once instead of leaving an inert element on the page.
    for (const tag of new Set(tags)) if (tag.startsWith('pk-') && !reg[tag] && !reported.has(tag)) { reported.add(tag); log.warn(`<${tag}> is not a Plainkit element (no such tag in the registry): check the spelling`, { tag }); }
    const plan = planLoad(tags, reg, new Set(loaded.keys()));
    await Promise.all(plan.map(({ tag, path }) => {
        const started = globalThis.performance?.now?.() ?? Date.now();
        const p = import(new URL(path, registry).href);
        loaded.set(tag, p);
        // Both outcomes are logged here, so the promise handed back never rejects.
        return p.then(() => { if (isLogEnabled('debug', 'loader')) log.debug(`loaded <${tag}> in ${Math.round((globalThis.performance?.now?.() ?? Date.now()) - started)} ms`, { tag, path }); }, error => { loaded.delete(tag); log.error(`could not load <${tag}> from ${path}`, error); });
    }));
    return plan.map(p => p.tag);
}

export function observeElements(root = document, options) {
    if (typeof MutationObserver === 'undefined' || observed.has(root)) return null;
    observed.add(root);
    const seen = new WeakSet();
    const mo = new MutationObserver(records => {
        for (const r of records) for (const n of r.addedNodes) if (n.nodeType === 1 && !seen.has(n)) { seen.add(n); loadElements(n, options); }
    });
    mo.observe(root.documentElement ?? root, { childList: true, subtree: true });
    return mo;
}
