// GENERATED by tools/build.mjs from elements/gallery/: do not edit.
import { PkElement, define } from '../../js/element.js';
import { normalizeOptions, toQuery, EMBED_URL } from '../../js/gallery-options.js';

export function frameUrl(props, base = EMBED_URL) {
    const { src, theme, height: _height, ...rest } = props;
    const query = toQuery({ chrome: 'none', ...normalizeOptions({ ...rest, theme: theme === 'auto' ? '' : theme }) });
    return `${new URL(src || base, globalThis.location?.href).href}?${query}`;
}

export function reportedHeight(event, frameWindow, origin) {
    if (event.source !== frameWindow || event.origin !== origin || event.data?.type !== 'pk-gallery-height') return 0;
    const h = Number(event.data.height);
    return Number.isFinite(h) && h > 0 && h < 100000 ? Math.ceil(h) : 0;
}

const behaviour = Base => class extends Base {
    connected() {
        if (this.$m) return;
        this.$m = e => {
            const h = this.height ? 0 : reportedHeight(e, this.part('frame').contentWindow, this.$o);
            if (h) this.style.setProperty('--pk-gallery-height', `${h}px`);
        };
        addEventListener('message', this.$m);
    }
    disconnected() { removeEventListener('message', this.$m); this.$m = null; }
    updated() {
        const frame = this.part('frame'), url = frameUrl(this.$);
        this.$o = new URL(url).origin;
        if (frame.getAttribute('src') !== url) frame.setAttribute('src', url);
        if (this.height) this.style.setProperty('--pk-gallery-height', `${this.height}px`); else if (this.$hadHeight) this.style.removeProperty('--pk-gallery-height');
        this.$hadHeight = Boolean(this.height);
    }
};
export default define(class extends behaviour(PkElement) {
    static tag = "pk-gallery";
    static props = {"kind":{"type":"string","default":"","reflect":false},"group":{"type":"string","default":"","reflect":false},"control":{"type":"string","default":"","reflect":false},"theme":{"type":"enum","default":"auto","values":["auto","dark","light"],"reflect":true},"width":{"type":"enum","default":"desktop","values":["desktop","phone"],"reflect":true},"filter":{"type":"string","default":"","reflect":false},"chrome":{"type":"enum","default":"none","values":["none","full"],"reflect":true},"height":{"type":"number","default":0,"reflect":false},"src":{"type":"string","default":"","reflect":false}};
    static delegatesFocus = false;
    static formAssociated = false;
    static template = "<iframe part=\"frame\" title=\"SDK gallery\" loading=\"lazy\"></iframe>";
    static css = ":host { display: block; }\n[part=\"frame\"] { display: block; inline-size: 100%; block-size: var(--pk-gallery-height, 28rem); border: 0; }\n";
});
