// GENERATED by tools/build.mjs from elements/button-group/: do not edit.
import { PkElement, define } from '../../js/element.js';
export function afterToggle(mode, states, changed) {
    if (mode !== 'single') return states;
    return states.map((s, i) => i === changed);
}
const behaviour = Base => class extends Base {
    connected() {
        if (this.$init) return;
        this.$init = true;
        this.addEventListener('pk-toggle', e => {
            if (this.mode !== 'single') return;
            const all = [...this.querySelectorAll('pk-button[toggle]')];
            const i = all.indexOf(e.target);
            if (i < 0) return;
            const next = afterToggle('single', all.map(b => b.pressed), i);
            all.forEach((b, n) => { b.pressed = next[n]; });
        });
    }
};
export default define(class extends behaviour(PkElement) {
    static tag = "pk-button-group";
    static props = {"orientation":{"type":"enum","default":"horizontal","values":["horizontal","vertical"],"reflect":true},"fill":{"type":"boolean","default":false,"reflect":true},"label":{"type":"string","default":"","reflect":false},"mode":{"type":"enum","default":"none","values":["none","single","multi"],"reflect":true}};
    static delegatesFocus = false;
    static formAssociated = false;
    static template = "<div part=\"group\" class=\"g\" role=\"group\" aria-label=\"{{label}}\"><slot></slot></div>";
    static css = ":host { display: inline-block; position: relative; }\n:host([fill]) { display: block; }\n.g { display: flex; }\n:host([orientation=\"vertical\"]) .g { flex-direction: column; }\n::slotted(*) { --pk-button-radius: 0; }\n::slotted(:first-child) { --pk-button-radius: var(--radius-sm) 0 0 var(--radius-sm); }\n::slotted(:last-child) { --pk-button-radius: 0 var(--radius-sm) var(--radius-sm) 0; }\n::slotted(:first-child:last-child) { --pk-button-radius: var(--radius-sm); }\n::slotted(:not(:first-child)) { margin-inline-start: -1px; }\n::slotted(:hover), ::slotted(:focus-within), ::slotted([pressed]) { position: relative; z-index: 1; }\n:host([orientation=\"vertical\"]) ::slotted(:first-child) { --pk-button-radius: var(--radius-sm) var(--radius-sm) 0 0; }\n:host([orientation=\"vertical\"]) ::slotted(:last-child) { --pk-button-radius: 0 0 var(--radius-sm) var(--radius-sm); }\n:host([orientation=\"vertical\"]) ::slotted(:not(:first-child)) { margin-inline-start: 0; margin-top: -1px; }\n:host([fill]) ::slotted(*) { flex: 1 1 0; }\n";
});
