// GENERATED by tools/build.mjs from elements/tab/: do not edit.
import { PkElement, define } from '../../js/element.js';
const behaviour = Base => class extends Base {
    connected() {
        if (!this.slot) this.slot = 'tab';
        if (!this.$x) { this.$x = true; this.part('close').addEventListener('click', e => { e.stopPropagation(); this.emit('pk-tab-close', { value: this.value }); }); }
        this.updated();
    }
    updated() { this.part('close').tabIndex = this.selected ? 0 : -1; this.aria({ role: 'tab', ariaSelected: String(this.selected), ariaDisabled: this.disabled ? 'true' : null }); }
};
export default define(class extends behaviour(PkElement) {
    static tag = "pk-tab";
    static props = {"value":{"type":"string","default":"","reflect":true},"selected":{"type":"boolean","default":false,"reflect":true},"disabled":{"type":"boolean","default":false,"reflect":true},"count":{"type":"string","default":"","reflect":false},"closable":{"type":"boolean","default":false,"reflect":true},"only":{"type":"enum","default":"all","values":["all","phone","desktop"],"reflect":true}};
    static delegatesFocus = false;
    static formAssociated = false;
    static template = "<span part=\"label\"><slot></slot></span><span part=\"count\" data-if=\"count\">({{count}})</span><button part=\"close\" type=\"button\" aria-label=\"Close tab\" data-if=\"closable\">&#x2715;</button>";
    static css = ":host { display: inline-flex; align-items: center; gap: var(--space-1); padding: var(--space-2) var(--space-4); border-bottom: 2px solid transparent; color: var(--pk-tab-fg, var(--color-muted)); font-size: var(--text-read); cursor: pointer; touch-action: manipulation; user-select: none; }\n:host(:hover) { color: var(--color-text); }\n:host([selected]) { color: var(--color-text); border-bottom-color: var(--color-accent); }\n:host([disabled]) { opacity: 0.45; cursor: not-allowed; }\n:host(:focus-visible) { outline: var(--focus-ring); outline-offset: -2px; }\n:host([only=\"phone\"]) { display: none; }\n[part=\"count\"] { color: var(--color-muted); }\n[part=\"close\"] { font: inherit; font-size: var(--text-sm); color: var(--color-muted); background: transparent; border: 0; padding: 0 0.35rem; margin-left: -0.25rem; cursor: pointer; }\n[part=\"close\"]:hover { color: var(--color-text); }\n@media (max-width: 640px) {\n    :host { min-height: var(--touch-target); }\n    :host([only=\"phone\"]) { display: inline-flex; }\n    :host([only=\"desktop\"]) { display: none; }\n}\n";
});
