// GENERATED by tools/build.mjs from elements/scroll-progress/: do not edit.
import { PkElement, define } from '../../js/element.js';
import { scrollProgress } from '../../js/scroll-aids.js';

const behaviour = Base => class extends Base {
    connected() { this.$f = () => this.measure(); this.bind(); this.measure(); }
    disconnected() { this.unbind(); }
    changed(name) { if (name === 'for' && this.isConnected) { this.unbind(); this.bind(); this.measure(); } }
    get scrollerEl() { return this.for ? document.querySelector(this.for) : null; }
    bind() { this.$t = this.scrollerEl ?? window; this.$t.addEventListener('scroll', this.$f, { passive: true }); window.addEventListener('resize', this.$f); }
    unbind() { this.$t?.removeEventListener('scroll', this.$f); window.removeEventListener('resize', this.$f); }
    measure() {
        const s = this.scrollerEl ?? document.scrollingElement;
        this.style.setProperty('--pk-progress', String(scrollProgress(s.scrollTop, s.scrollHeight, this.scrollerEl ? s.clientHeight : innerHeight)));
    }
};
export default define(class extends behaviour(PkElement) {
    static tag = "pk-scroll-progress";
    static props = {"for":{"type":"string","default":"","reflect":true}};
    static delegatesFocus = false;
    static formAssociated = false;
    static template = "<div part=\"bar\" aria-hidden=\"true\"></div>";
    static css = "/* pk-scroll-progress: fixed to the top of the screen; the bar scales from the start edge. */\n:host { --pk-progress: 0; position: fixed; inset: 0 0 auto 0; z-index: var(--z-sticky); height: 3px; pointer-events: none; }\n\n[part=\"bar\"] { height: 100%; background: var(--color-accent); transform: scaleX(var(--pk-progress)); transform-origin: left; }\n\n:host(:dir(rtl)) [part=\"bar\"] { transform-origin: right; }\n\n@media (prefers-reduced-motion: no-preference) { [part=\"bar\"] { transition: transform 0.1s linear; } }\n";
});
