// GENERATED by tools/build.mjs from elements/avatar/: do not edit.
import { PkElement, define } from '../../js/element.js';

export function initials(name, max = 2) {
    const words = String(name ?? '').trim().split(/\s+/).filter(Boolean);
    if (!words.length) return '?';
    const chars = words.length === 1 ? Array.from(words[0]).slice(0, max) : [words[0], words[words.length - 1]].map(w => Array.from(w)[0]);
    return chars.slice(0, max).join('').toUpperCase();
}

export function colourSlot(name, count = 5) {
    const h = Array.from(String(name ?? '')).reduce((acc, ch) => (acc * 31 + ch.codePointAt(0)) >>> 0, 0);
    return (h % count) + 1;
}

export const groupOverflow = (people, max = 4) => ({ shown: people.slice(0, max), more: Math.max(0, people.length - max) });

const behaviour = Base => class extends Base {
    connected() {
        const img = this.part('image');
        if (!this.$e) { this.$e = () => { this.$bad = this.src; img.removeAttribute('src'); img.hidden = true; }; img.addEventListener('error', this.$e); }
    }
    updated() {
        const img = this.part('image');
        if (this.src && this.src !== this.$bad) { if (img.getAttribute('src') !== this.src) img.setAttribute('src', this.src); img.hidden = false; } else { img.removeAttribute('src'); img.hidden = true; }
        this.part('initials').textContent = initials(this.name);
        this.dataset.slot = this.colour || String(colourSlot(this.name));
        this.aria({ role: 'img', ariaLabel: [this.name, this.status === 'none' ? '' : this.status].filter(Boolean).join(', ') });
    }
};
export default define(class extends behaviour(PkElement) {
    static tag = "pk-avatar";
    static props = {"name":{"type":"string","default":"","reflect":false},"src":{"type":"string","default":"","reflect":false},"size":{"type":"enum","default":"md","values":["md","sm","lg"],"reflect":true},"shape":{"type":"enum","default":"circle","values":["circle","square"],"reflect":true},"status":{"type":"enum","default":"none","values":["none","online","away","busy"],"reflect":true},"colour":{"type":"string","default":"","reflect":false}};
    static delegatesFocus = false;
    static formAssociated = false;
    static template = "<img part=\"image\" data-if=\"src\" alt=\"\"><span part=\"initials\"></span><span part=\"status\"></span>";
    static css = ":host { --_bg: var(--pk-avatar-bg, var(--chart-1)); --_s: var(--pk-avatar-size, calc(var(--space-8) + var(--space-1))); position: relative; display: inline-flex; align-items: center; justify-content: center; flex: none; inline-size: var(--_s); block-size: var(--_s); overflow: hidden; border-radius: var(--radius-round); background: var(--_bg); color: var(--pk-avatar-fg, var(--chart-on)); font-size: calc(var(--_s) * 0.4); font-weight: 600; line-height: 1; text-transform: uppercase; }\n:host([size=\"sm\"]) { --_s: var(--pk-avatar-size, var(--space-6)); }\n:host([size=\"lg\"]) { --_s: var(--pk-avatar-size, var(--space-12)); }\n:host([shape=\"square\"]) { border-radius: var(--radius-md); }\n:host([data-slot=\"2\"]) { --_bg: var(--pk-avatar-bg, var(--chart-2)); }\n:host([data-slot=\"3\"]) { --_bg: var(--pk-avatar-bg, var(--chart-3)); }\n:host([data-slot=\"4\"]) { --_bg: var(--pk-avatar-bg, var(--chart-4)); }\n:host([data-slot=\"5\"]) { --_bg: var(--pk-avatar-bg, var(--chart-5)); }\n:host([data-slot=\"muted\"]) { --_bg: var(--pk-avatar-bg, var(--color-surface-alt)); color: var(--color-muted); }\n[part=\"image\"] { position: absolute; inset: 0; inline-size: 100%; block-size: 100%; object-fit: cover; }\n[part=\"status\"] { position: absolute; inset-block-end: 0; inset-inline-end: 0; display: none; inline-size: 28%; block-size: 28%; border: 2px solid var(--color-panel); border-radius: var(--radius-round); background: var(--color-muted); }\n:host([status=\"online\"]) [part=\"status\"] { display: block; background: var(--delta-up); }\n:host([status=\"away\"]) [part=\"status\"] { display: block; background: var(--chart-2); }\n:host([status=\"busy\"]) [part=\"status\"] { display: block; background: var(--delta-down); }\n";
});
