// GENERATED by tools/build.mjs from elements/icon/: do not edit.
import { PkElement, define } from '../../js/element.js';

export const spriteUrl = (moduleUrl = import.meta.url) => new URL(/\/elements\/icon\/[^/]*$/.test(moduleUrl) ? '../../icons.svg' : '../icons.svg', moduleUrl).href;

export const iconHref = (name, sprite = spriteUrl()) => (String(name ?? '').trim() ? `${sprite}#${String(name).trim()}` : '');

const behaviour = Base => class extends Base {
    updated() {
        const href = iconHref(this.name);
        const use = this.part('use');
        if (href) { if (use.getAttribute('href') !== href) use.setAttribute('href', href); } else use.removeAttribute('href');
        if (this.label) this.aria({ role: 'img', ariaLabel: this.label, ariaHidden: null });
        else this.aria({ role: null, ariaLabel: null, ariaHidden: 'true' });
    }
};
export default define(class extends behaviour(PkElement) {
    static tag = "pk-icon";
    static props = {"name":{"type":"string","default":"","reflect":true},"size":{"type":"enum","default":"md","values":["sm","md","lg","xl"],"reflect":true},"label":{"type":"string","default":"","reflect":true}};
    static delegatesFocus = false;
    static formAssociated = false;
    static template = "<svg part=\"svg\" viewBox=\"0 0 24 24\" aria-hidden=\"true\" focusable=\"false\"><use part=\"use\"></use></svg>";
    static css = ":host { --_size: var(--pk-icon-size, 1.25em); display: inline-block; inline-size: var(--_size); block-size: var(--_size); flex: none; color: inherit; line-height: 0; vertical-align: -0.2em; }\n:host([size=\"sm\"]) { --_size: var(--pk-icon-size, var(--space-4)); }\n:host([size=\"lg\"]) { --_size: var(--pk-icon-size, var(--space-6)); }\n:host([size=\"xl\"]) { --_size: var(--pk-icon-size, var(--space-8)); }\nsvg { display: block; inline-size: 100%; block-size: 100%; fill: none; stroke: currentColor; stroke-width: 2; stroke-linecap: round; stroke-linejoin: round; }\n";
});
