// GENERATED by tools/build.mjs from elements/timeline-item/: do not edit.
import { PkElement, define } from '../../js/element.js';
const behaviour = Base => class extends Base {
    connected() { this.aria({ role: 'listitem' }); this.watchSlot('', () => this.requestUpdate()); }
    updated() { this.part('body').hidden = !this.shadowRoot.querySelector('slot:not([name])').assignedNodes({ flatten: true }).some(n => n.nodeType === 1 || n.textContent.trim() !== ''); }
};
export default define(class extends behaviour(PkElement) {
    static tag = "pk-timeline-item";
    static props = {"heading":{"type":"string","default":"","reflect":false},"time":{"type":"string","default":"","reflect":false},"status":{"type":"enum","default":"pending","values":["pending","done","active","danger"],"reflect":true}};
    static delegatesFocus = false;
    static formAssociated = false;
    static template = "<div part=\"marker\"></div><div part=\"content\"><div part=\"head\"><span part=\"heading\"><slot name=\"heading\">{{heading}}</slot></span><time part=\"time\" datetime=\"{{time}}\" data-if=\"time\"><slot name=\"time\">{{time}}</slot></time></div><div part=\"body\"><slot></slot></div></div>";
    static css = ":host { --_c: var(--color-muted); position: relative; display: grid; grid-template-columns: var(--space-4) 1fr; gap: 0 var(--space-3); padding-block-end: var(--space-4); }\n:host([status=\"done\"]) { --_c: var(--delta-up); }\n:host([status=\"active\"]) { --_c: var(--color-accent); }\n:host([status=\"danger\"]) { --_c: var(--delta-down); }\n[part=\"marker\"] { position: relative; justify-self: center; inline-size: var(--space-3); block-size: var(--space-3); margin-block-start: var(--space-1); border: 2px solid var(--_c); border-radius: var(--radius-round); background: var(--color-panel); }\n:host([status=\"done\"]) [part=\"marker\"], :host([status=\"active\"]) [part=\"marker\"] { background: var(--_c); }\n:host::before { content: \"\"; position: absolute; inset-block: var(--space-5) 0; inset-inline-start: calc(var(--space-2) - 1px); inline-size: 2px; background: var(--color-border); }\n:host(:last-child)::before { display: none; }\n[part=\"head\"] { display: flex; flex-wrap: wrap; align-items: baseline; justify-content: space-between; gap: var(--space-1) var(--space-3); }\n[part=\"heading\"] { font-weight: 600; }\n[part=\"time\"] { color: var(--color-muted); font-size: var(--text-meta); }\n[part=\"body\"] { color: var(--color-muted); }\n";
});
