// GENERATED by tools/build.mjs from elements/dropdown/: do not edit.
import { PkElement, define } from '../../js/element.js';
import { place, autoUpdate, onOutside, unplace } from '../../js/positioning.js';
import { moveFocus } from '../../js/menu-logic.js';

const rows = el => el.slotted().filter(i => i.localName === 'pk-menu-item' && !['header', 'divider'].includes(i.type) && !i.disabled);
const behaviour = Base => class extends Base {
    connected() {
        if (!this.$w) {
            this.$w = true; this.$s = { buffer: '', at: 0 };
            this.addEventListener('click', e => {
                const t = this.trigger;
                if (t && t.contains(e.target)) { this.$kb = e.detail === 0; this.request(this.open ? 'toggle' : null); return; }
            });
            this.addEventListener('pk-select', () => { if (!this.keepOpen && this.open) this.request('select'); });
            this.addEventListener('keydown', e => this.key(e));
            this.watchSlot('trigger', () => this.aria2());
        }
        this.aria2(); this.apply();
    }
    disconnected() { this.stop(); }
    get trigger() { return this.slotted('trigger')[0]; }
    aria2() { const t = this.trigger; if (t) { t.setAttribute('aria-haspopup', 'menu'); t.setAttribute('aria-expanded', String(this.open)); } }
    changed(name) { if (name === 'open') this.apply(); }
    show() { this.open = true; }
    hide() { this.open = false; }
    request(reason) {
        if (reason === null) { this.open = true; return; }
        if (this.emit('pk-close', { reason })) { this.open = false; if (reason !== 'outside') this.trigger?.focus({ preventScroll: true }); }
    }
    apply() {
        const menu = this.part('menu');
        this.stop(); this.aria2();
        if (!this.open) { unplace(menu); return; }
        const t = this.trigger; const options = { placement: this.placement, offset: 4 };
        if (t) { place(t, menu, options); this.$u = autoUpdate(t, menu, options); }
        this.$o = onOutside([this], e => this.request(e.type === 'keydown' ? 'escape' : 'outside'));
        if (this.$kb) rows(this)[0]?.focus({ preventScroll: true });
        this.$kb = false;
        this.emit('pk-open', {});
    }
    stop() { this.$u?.(); this.$o?.(); this.$u = this.$o = null; }
    key(e) {
        const t = this.trigger;
        if (t && t.contains(e.target)) {
            if (e.key === 'ArrowDown' || e.key === 'ArrowUp') { e.preventDefault(); this.open = true; const r = rows(this); (e.key === 'ArrowUp' ? r[r.length - 1] : r[0])?.focus({ preventScroll: true }); }
            return;
        }
        if (!this.open) return;
        if (e.key === 'Tab') { this.request('tab'); return; }
        moveFocus(e, rows(this), this.$s);
    }
};
export default define(class extends behaviour(PkElement) {
    static tag = "pk-dropdown";
    static props = {"open":{"type":"boolean","default":false,"reflect":true},"placement":{"type":"string","default":"bottom-start","reflect":true},"keepOpen":{"type":"boolean","default":false,"reflect":true},"mega":{"type":"boolean","default":false,"reflect":true}};
    static delegatesFocus = false;
    static formAssociated = false;
    static template = "<slot name=\"trigger\"></slot><div part=\"menu\" role=\"menu\"><slot></slot></div>";
    static css = "/* pk-dropdown: the trigger stays in flow; the menu is a fixed layer placed by the positioning helper. */\n:host { display: inline-block; }\n\n[part=\"menu\"] {\n    display: none;\n    position: fixed;\n    top: 0;\n    left: 0;\n    z-index: var(--z-pop);\n    box-sizing: border-box;\n    min-width: var(--pk-dropdown-min-w, 12rem);\n    max-width: calc(100vw - 2 * var(--space-4));\n    max-height: min(24rem, calc(100dvh - 2 * var(--space-4)));\n    overflow-y: auto;\n    overscroll-behavior: contain;\n    padding: var(--space-1);\n    background: var(--color-panel);\n    color: var(--color-text);\n    border: 1px solid var(--color-border);\n    border-radius: var(--radius-md);\n    box-shadow: var(--shadow-pop);\n    animation: menu-in 0.12s ease-out;\n}\n\n:host([open]) [part=\"menu\"] { display: block; }\n\n/* A mega menu: a wide panel whose items flow into columns; a single column when the screen is narrow. */\n:host([mega]) [part=\"menu\"] { width: min(48rem, calc(100vw - 2 * var(--space-4))); max-width: none; }\n\n:host([mega][open]) [part=\"menu\"] { display: grid; grid-template-columns: repeat(auto-fit, minmax(10rem, 1fr)); gap: var(--space-1) var(--space-4); align-content: start; }\n\n@keyframes menu-in { from { opacity: 0; transform: translateY(-2px); } }\n\n@media (prefers-reduced-motion: reduce) { [part=\"menu\"] { animation: none; } }\n";
});
