// GENERATED by tools/build.mjs from elements/breadcrumb/: do not edit.
import { PkElement, define } from '../../js/element.js';

export const DEFAULT_MAX = 4;
export const PHONE_MAX = 3;
export const PHONE_WIDTH = 640;

export const maxCrumbs = (width, max = DEFAULT_MAX, phoneMax = PHONE_MAX) => (width <= PHONE_WIDTH ? Math.min(max, phoneMax) : max);

export function hiddenCrumbs(count, max = DEFAULT_MAX, { head = 1, tail = 2 } = {}) {
    if (count <= max || count <= head + tail) return [];
    const out = [];
    for (let i = head; i < count - tail; i++) out.push(i);
    return out;
}

const behaviour = Base => class extends Base {
    connected() {
        if (!this.$w) {
            this.$w = true;
            this.watchSlot('', () => this.fold());
            this.part('more').addEventListener('click', () => { this.$open = true; this.part('more').setAttribute('aria-expanded', 'true'); this.fold(); this.emit('pk-expand', null); });
            this.$mq = globalThis.matchMedia('(max-width: 640px)'); this.$fold = () => this.fold();
        }
        this.$mq.addEventListener('change', this.$fold);
        this.fold();
    }
    disconnected() { this.$mq?.removeEventListener('change', this.$fold); }
    changed(name) { if (name === 'max') this.fold(); }
    fold() {
        const crumbs = this.slotted();
        const hide = this.$open ? [] : hiddenCrumbs(crumbs.length, maxCrumbs(globalThis.innerWidth, this.max));
        crumbs.forEach((c, i) => c.toggleAttribute('data-folded', hide.includes(i)));
        this.toggleAttribute('data-has-fold', hide.length > 0);
        const last = crumbs[crumbs.length - 1];
        if (last && !crumbs.some(c => c.hasAttribute('aria-current'))) last.setAttribute('aria-current', 'page');
        this.part('more').setAttribute('aria-label', `Show ${hide.length} hidden pages`);
    }
};
export default define(class extends behaviour(PkElement) {
    static tag = "pk-breadcrumb";
    static props = {"label":{"type":"string","default":"Breadcrumb","reflect":true},"max":{"type":"number","default":4,"reflect":true}};
    static delegatesFocus = false;
    static formAssociated = false;
    static template = "<nav part=\"nav\" aria-label=\"{{label}}\"><ol part=\"list\"><li part=\"item\"><slot></slot></li><li part=\"fold\"><button type=\"button\" part=\"more\" aria-label=\"Show hidden pages\" aria-expanded=\"false\" data-action=\"expand\"></button></li></ol></nav>";
    static css = "/* pk-breadcrumb: a trail of links with a chevron between them. The element marks folded crumbs with [data-folded]; the fold button shows only then. */\n:host { display: block; font-size: var(--text-read); }\n\n[part=\"list\"] { display: flex; flex-wrap: wrap; align-items: center; gap: var(--space-1) var(--space-2); margin: 0; padding: 0; list-style: none; }\n\n[part=\"item\"], [part=\"fold\"] { margin: 0; }\n\n[part=\"item\"] { display: contents; }\n\n::slotted(a), ::slotted(span) { display: inline-flex; align-items: center; min-height: 2rem; color: var(--color-link); text-decoration: none; }\n\n::slotted(a:hover) { text-decoration: underline; }\n\n::slotted(a:not(:last-child))::after, ::slotted(span:not(:last-child))::after { content: \"\\203A\"; margin-inline-start: var(--space-2); color: var(--color-muted); }\n\n::slotted([aria-current=\"page\"]) { color: var(--color-text); font-weight: 600; }\n\n::slotted([data-folded]) { display: none; }\n\n::slotted(*) { order: 2; }\n\n::slotted(:first-child) { order: 0; }\n\n[part=\"fold\"] { display: none; order: 1; }\n\n:host([data-has-fold]) [part=\"fold\"] { display: list-item; }\n\n[part=\"more\"] { min-width: 2rem; min-height: 2rem; padding: 0 var(--space-2); border: 1px solid var(--color-border); border-radius: var(--radius-md); background: transparent; color: var(--color-muted); font: inherit; cursor: pointer; }\n\n[part=\"more\"]::before { content: \"\\2026\"; }\n\n[part=\"more\"]:hover { background: var(--color-surface-alt); }\n\n[part=\"more\"]:focus-visible { outline: var(--focus-ring); outline-offset: 2px; }\n\n@media (max-width: 640px) { ::slotted(a), [part=\"more\"] { min-height: var(--touch-target); } [part=\"more\"] { min-width: var(--touch-target); } }\n";
});
