// GENERATED by tools/build.mjs from elements/back-to-top/: do not edit.
import { PkElement, define } from '../../js/element.js';
import { showBackToTop, scrollBehavior } from '../../js/scroll-aids.js';

const behaviour = Base => class extends Base {
    connected() {
        if (!this.$w) { this.$w = true; this.part('button').addEventListener('click', () => this.top()); }
        this.$f = () => { this.visible = showBackToTop((this.scrollerEl ?? document.scrollingElement).scrollTop, this.threshold); };
        this.$t = this.scrollerEl ?? window; this.$t.addEventListener('scroll', this.$f, { passive: true }); this.$f();
    }
    disconnected() { this.$t?.removeEventListener('scroll', this.$f); }
    get scrollerEl() { return this.for ? document.querySelector(this.for) : null; }
    top() {
        const s = this.scrollerEl ?? window;
        s.scrollTo({ top: 0, behavior: scrollBehavior(globalThis.matchMedia('(prefers-reduced-motion: reduce)').matches) });
        const home = document.querySelector('[data-scroll-top], main, body'); home?.setAttribute?.('tabindex', home.getAttribute('tabindex') ?? '-1'); home?.focus({ preventScroll: true });
    }
};
export default define(class extends behaviour(PkElement) {
    static tag = "pk-back-to-top";
    static props = {"for":{"type":"string","default":"","reflect":true},"threshold":{"type":"number","default":400,"reflect":true},"label":{"type":"string","default":"Back to top","reflect":true},"visible":{"type":"boolean","default":false,"reflect":true}};
    static delegatesFocus = false;
    static formAssociated = false;
    static template = "<button type=\"button\" part=\"button\" data-action=\"top\"><span part=\"icon\" aria-hidden=\"true\"></span><slot>{{label}}</slot></button>";
    static css = "/* pk-back-to-top: a floating pill at the end of the screen, clear of the safe area; hidden until the reader has scrolled. */\n:host { position: fixed; inset-block-end: max(var(--space-4), env(safe-area-inset-bottom)); inset-inline-end: max(var(--space-4), env(safe-area-inset-right)); z-index: var(--z-sticky); display: none; }\n\n:host([visible]) { display: block; }\n\n[part=\"button\"] { display: inline-flex; align-items: center; gap: var(--space-2); min-height: var(--touch-target); padding: var(--space-1) var(--space-4); border: 1px solid var(--color-border); border-radius: var(--radius-pill); background: var(--color-panel); color: var(--color-text); box-shadow: var(--shadow-pop); font: inherit; font-size: var(--text-read); cursor: pointer; }\n\n[part=\"icon\"]::before { content: \"\\2191\"; }\n\n[part=\"button\"]:hover { background: var(--color-surface-alt); }\n\n[part=\"button\"]:focus-visible { outline: var(--focus-ring); outline-offset: 2px; }\n";
});
