// GENERATED by tools/build.mjs from elements/accordion/: do not edit.
import { PkElement, define } from '../../js/element.js';
const behaviour = Base => class extends Base {
    connected() {
        if (this.$t) return;
        this.$t = e => {
            if (!this.exclusive || !e.detail?.open) return;
            for (const item of this.slotted()) if (item !== e.target && item.open) item.open = false;
        };
        this.addEventListener('pk-toggle', this.$t);
    }
};
export default define(class extends behaviour(PkElement) {
    static tag = "pk-accordion";
    static props = {"exclusive":{"type":"boolean","default":false,"reflect":true},"flush":{"type":"boolean","default":false,"reflect":true}};
    static delegatesFocus = false;
    static formAssociated = false;
    static template = "<slot></slot>";
    static css = ":host { display: flex; flex-direction: column; gap: var(--space-2); }\n:host([flush]) { gap: 0; overflow: hidden; border: 1px solid var(--color-border); border-radius: var(--radius-md); }\n:host([flush]) ::slotted(pk-accordion-item) { border-width: 0 0 1px; border-radius: 0; }\n:host([flush]) ::slotted(pk-accordion-item:last-child) { border-block-end-width: 0; }\n";
});
