// GENERATED by tools/build.mjs from elements/toolbar/: do not edit.
import { PkElement, define } from '../../js/element.js';
const behaviour = Base => class extends Base {
    connected() { this.watchSlot('actions', () => this.requestUpdate()); }
    updated() { this.part('actions').hidden = this.slotted('actions').length === 0; }
};
export default define(class extends behaviour(PkElement) {
    static tag = "pk-toolbar";
    static props = {"heading":{"type":"string","default":"","reflect":true},"note":{"type":"string","default":"","reflect":true}};
    static delegatesFocus = false;
    static formAssociated = false;
    static template = "<div part=\"toolbar\"><div part=\"lead\"><strong part=\"title\" data-if=\"heading\">{{heading}}</strong><span part=\"note\" data-if=\"note\">{{note}}</span><slot></slot></div><div part=\"actions\"><slot name=\"actions\"></slot></div></div>";
    static css = "/* pk-toolbar: a lead (title, note, anything else) with an actions area at the right. Wraps by its own width and stacks on a phone. */\n:host { display: block; inline-size: 100%; container-type: inline-size; min-inline-size: 0; }\n[part=\"toolbar\"] { display: flex; flex-wrap: wrap; align-items: center; justify-content: space-between; gap: var(--space-2) var(--space-4); margin: var(--pk-toolbar-margin, var(--space-1) 0 var(--space-3) 0); }\n[part=\"lead\"] { display: flex; flex-wrap: wrap; align-items: baseline; gap: var(--space-1) var(--space-3); min-inline-size: 0; }\n[part=\"title\"] { color: var(--color-text); }\n[part=\"note\"] { color: var(--color-muted); font-size: var(--text-md); }\n[part=\"actions\"] { display: flex; flex-wrap: wrap; align-items: center; gap: var(--space-2); margin-inline-start: auto; }\n@container (max-width: 46rem) {\n    [part=\"lead\"], [part=\"actions\"] { inline-size: 100%; margin-inline-start: 0; }\n    ::slotted([slot=\"actions\"]) { min-block-size: var(--touch-target); }\n}\n";
});
