// GENERATED by tools/build.mjs from elements/empty-state/: do not edit.
import { PkElement, define } from '../../js/element.js';
const filled = (el, name) => el.shadowRoot.querySelector(name ? `slot[name="${name}"]` : 'slot:not([name])').assignedNodes({ flatten: true }).some(n => n.nodeType === 1 || n.textContent.trim() !== '');

const behaviour = Base => class extends Base {
    connected() { for (const s of ['heading', '', 'icon', 'actions']) this.watchSlot(s, () => this.requestUpdate()); }
    updated() {
        this.part('heading').hidden = !this.heading && !filled(this, 'heading');
        this.part('description').hidden = !this.description && !filled(this, '');
        this.part('icon').hidden = !filled(this, 'icon');
        this.part('actions').hidden = !filled(this, 'actions');
        this.aria({ role: this.announce ? 'status' : null });
    }
};
export default define(class extends behaviour(PkElement) {
    static tag = "pk-empty-state";
    static props = {"heading":{"type":"string","default":"","reflect":false},"level":{"type":"number","default":3,"reflect":false},"description":{"type":"string","default":"","reflect":false},"tone":{"type":"enum","default":"default","values":["default","compact","boxed","error"],"reflect":true},"announce":{"type":"boolean","default":false,"reflect":true}};
    static delegatesFocus = false;
    static formAssociated = false;
    static template = "<div part=\"root\"><span part=\"icon\"><slot name=\"icon\"></slot></span><div part=\"heading\" role=\"heading\" aria-level=\"{{level}}\"><slot name=\"heading\">{{heading}}</slot></div><p part=\"description\"><slot>{{description}}</slot></p><div part=\"actions\"><slot name=\"actions\"></slot></div></div>";
    static css = ":host { display: block; }\n[part=\"root\"] { display: flex; flex-direction: column; align-items: center; justify-content: center; gap: var(--space-2); padding: var(--pk-empty-state-padding, var(--space-8) var(--space-6)); text-align: center; color: var(--color-muted); }\n:host([tone=\"compact\"]) [part=\"root\"] { padding: var(--pk-empty-state-padding, var(--space-3) var(--space-4)); }\n:host([tone=\"boxed\"]) [part=\"root\"] { border: 1px dashed var(--color-border); border-radius: var(--radius-md); }\n:host([tone=\"error\"]) [part=\"root\"] { border: 1px solid var(--color-notice-error); border-radius: var(--radius-md); }\n[part=\"icon\"] { opacity: 0.6; }\n[part=\"heading\"] { margin: 0; font-size: var(--text-lg); font-weight: 600; color: var(--color-text); }\n[part=\"description\"] { margin: 0; max-inline-size: 40rem; line-height: 1.5; }\n[part=\"actions\"] { display: flex; flex-wrap: wrap; justify-content: center; gap: var(--space-2); margin-block-start: var(--space-2); }\n";
});
