// GENERATED by tools/build.mjs from elements/grid/: do not edit.
import { PkElement, define } from '../../js/element.js';
export const ratioColumns = text => {
    const t = String(text).trim();
    return /^\d+(\.\d+)?(\s*:\s*\d+(\.\d+)?)+$/.test(t) && t.split(':').every(p => Number(p) > 0) ? t.split(':').map(p => `minmax(0, ${Number(p)}fr)`).join(' ') : null;
};

const behaviour = Base => class extends Base {
    updated() {
        const ok = this.hasAttribute('min') && this.min.trim() !== '' && CSS.supports('inline-size', this.min);
        if (ok) this.style.setProperty('--pk-grid-min', this.min); else this.style.removeProperty('--pk-grid-min');
        const r = this.ratio ? ratioColumns(this.ratio) : null;
        if (this.ratio && !r) this.warnOnce('ratio', `ratio="${this.ratio}" is not like 2:1: using equal columns`);
        if (r) this.style.setProperty('--pk-grid-ratio', r); else this.style.removeProperty('--pk-grid-ratio');
        const n = Math.floor(this.columns);
        if (n > 0) this.style.setProperty('--pk-grid-columns', String(n)); else this.style.removeProperty('--pk-grid-columns');
    }
};
export default define(class extends behaviour(PkElement) {
    static tag = "pk-grid";
    static props = {"min":{"type":"string","default":"16rem","reflect":true},"columns":{"type":"number","default":0,"reflect":true},"ratio":{"type":"string","default":"","reflect":true},"gap":{"type":"enum","default":"md","values":["none","xs","sm","md","lg","xl"],"reflect":true}};
    static delegatesFocus = false;
    static formAssociated = false;
    static template = "<slot></slot>";
    static css = ":host {\n    --_g: var(--space-4);\n    --_share: calc((100% - (var(--pk-grid-columns) - 1) * var(--_g)) / var(--pk-grid-columns));\n    display: grid;\n    inline-size: 100%; /* a grid has no intrinsic width of its own: fill the container, also inside a shrink-to-fit or flex-row parent */\n    min-inline-size: 0;\n    box-sizing: border-box;\n    --_cols: repeat(auto-fit, minmax(max(min(var(--pk-grid-min, 16rem), 100%), var(--_share, 0px)), 1fr));\n    grid-template-columns: var(--pk-grid-ratio, var(--_cols));\n    gap: var(--_g);\n}\n:host([hidden]) { display: none; }\n:host([gap=\"none\"]) { --_g: 0px; }\n:host([gap=\"xs\"]) { --_g: var(--space-1); }\n:host([gap=\"sm\"]) { --_g: var(--space-2); }\n:host([gap=\"lg\"]) { --_g: var(--space-6); }\n:host([gap=\"xl\"]) { --_g: var(--space-8); }\n::slotted(*) { min-inline-size: 0; }\n@media (width <= 640px) { :host { grid-template-columns: var(--_cols); } }\n";
});
