// GENERATED by tools/build.mjs from elements/field/: do not edit.
import { PkElement, define } from '../../js/element.js';
export const counterText = (length, max) => (max > 0 ? `${length} / ${max}` : String(length));
export function counterState(length, max) {
    if (!(max > 0)) return 'ok';
    if (length > max) return 'over';
    return length >= max * 0.9 ? 'near' : 'ok';
}
export const describe = (...parts) => parts.filter(Boolean).join(' ');

const behaviour = Base => class extends Base {
    connected() {
        if (this.$init) return;
        this.$init = true;
        this.watchSlot('', () => this.wire());
        this.watchSlot('label-action', () => this.count());
        this.addEventListener('input', () => this.count());
        this.part('label').addEventListener('click', e => { if (!e.composedPath().some(n => n.getAttribute?.('slot') === 'label-action')) this.control()?.focus(); });
    }
    control() { return this.slotted().find(e => e.localName.startsWith('pk-') || ['input', 'select', 'textarea'].includes(e.localName)) ?? null; }
    updated() { this.wire(); }
    wire() {
        const c = this.control();
        if (!c) return;
        const mine = c.$fieldLabel ?? '';
        if ('label' in c) { if (!c.label || c.label === mine) { c.label = this.label; c.$fieldLabel = this.label; } } else if (this.label && !c.getAttribute('aria-label')) c.setAttribute('aria-label', this.label);
        if (this.required && 'required' in c) c.required = true;
        const text = describe(this.help, this.error, this.warning);
        if ('description' in c) c.description = text; else if (text) c.setAttribute('aria-description', text); else c.removeAttribute('aria-description');
        if ('invalid' in c) { this.flag(c, 'invalid', Boolean(this.error)); this.flag(c, 'warning', Boolean(this.warning) && !this.error); }
        else { c.toggleAttribute('data-invalid', Boolean(this.error)); if (this.error) c.setAttribute('aria-invalid', 'true'); else c.removeAttribute('aria-invalid'); }
        this.count();
    }
    flag(c, name, on) { c.$byField ??= {}; if (on) { c[name] = true; c.$byField[name] = true; } else if (c.$byField[name]) { c[name] = false; c.$byField[name] = false; } }
    count() {
        const c = this.control(); const n = this.part('count');
        if (!c || !(this.max > 0)) n.textContent = '';
        else { const length = String(c.value ?? '').length; n.textContent = counterText(length, this.max); n.dataset.state = counterState(length, this.max); }
        const helpOn = Boolean(this.help) || this.slotted('help').length > 0;
        this.part('label').hidden = !this.label && this.slotted('label').length === 0 && this.slotted('label-action').length === 0;
        this.part('help').hidden = !helpOn;
        this.part('foot').hidden = !helpOn && !this.error && !this.warning && n.textContent === '';
    }
};
export default define(class extends behaviour(PkElement) {
    static tag = "pk-field";
    static props = {"label":{"type":"string","default":"","reflect":true},"help":{"type":"string","default":"","reflect":true},"error":{"type":"string","default":"","reflect":true},"warning":{"type":"string","default":"","reflect":true},"required":{"type":"boolean","default":false,"reflect":true},"max":{"type":"number","default":0,"reflect":false},"layout":{"type":"enum","default":"stack","values":["stack","row","inline"],"reflect":true},"size":{"type":"enum","default":"md","values":["md","sm"],"reflect":true}};
    static delegatesFocus = true;
    static formAssociated = false;
    static template = "<div part=\"field\" class=\"field\"><div part=\"label\" class=\"lab\"><slot name=\"label\">{{label}}</slot><span part=\"required\" class=\"req\" data-if=\"required\" aria-hidden=\"true\">*</span><slot name=\"label-action\"></slot></div><slot></slot><div part=\"foot\" class=\"foot\"><span part=\"help\" class=\"help\"><slot name=\"help\">{{help}}</slot></span><span part=\"error\" class=\"msg err\" role=\"status\">{{error}}</span><span part=\"warning\" class=\"msg warn\" role=\"status\">{{warning}}</span><span part=\"count\" class=\"count\"></span></div></div>";
    static css = ":host { display: block; }\n.field { display: grid; gap: var(--gap-label-input); min-width: 0; }\n.lab { color: var(--pk-field-label, var(--color-text)); font-size: var(--text-read); font-weight: 500; cursor: default; }\n::slotted([slot=\"label-action\"]) { margin-inline-start: var(--space-2); vertical-align: middle; }\n.req { margin-inline-start: 0.2em; color: var(--field-error); }\n.foot { display: flex; flex-wrap: wrap; justify-content: space-between; gap: var(--space-1) var(--space-3); }\n.help, .msg, .count { font-size: var(--text-meta); }\n.help { flex: 1 1 auto; color: var(--field-muted); }\n.err { color: var(--field-error); }\n.warn { color: var(--field-warn); }\n.msg:empty, .help:empty, .count:empty { display: none; }\n.count { flex: none; margin-inline-start: auto; color: var(--field-muted); font-variant-numeric: tabular-nums; }\n.count[data-state=\"near\"] { color: var(--field-warn); }\n.count[data-state=\"over\"] { color: var(--field-error); font-weight: 600; }\n:host([layout=\"row\"]) .field { grid-template-columns: var(--pk-field-label-width, 9rem) minmax(0, 1fr); align-items: center; column-gap: var(--space-4); }\n:host([layout=\"row\"]) .foot { grid-column: 2; }\n@media (max-width: 640px) { :host([layout=\"row\"]) .field { grid-template-columns: minmax(0, 1fr); } :host([layout=\"row\"]) .foot { grid-column: 1; } }\n:host([layout=\"inline\"]) .field { display: flex; align-items: center; gap: var(--space-2); }\n:host([size=\"sm\"]) .field { gap: var(--space-1); }\n:host([size=\"sm\"]) .lab { font-size: var(--text-meta); }\n";
});
