// GENERATED by tools/build.mjs from elements/form/: do not edit.
import { PkElement, define } from '../../js/element.js';
const KEYS = [['valueMissing', 'required'], ['typeMismatch', 'type'], ['patternMismatch', 'pattern'], ['tooShort', 'minlength'], ['tooLong', 'maxlength'], ['rangeUnderflow', 'min'], ['rangeOverflow', 'max'], ['stepMismatch', 'step'], ['badInput', 'bad-input'], ['customError', 'custom']];

export function messageFor(control) {
    const v = control.validity;
    if (!v || v.valid !== false) return '';
    const fallback = control.getAttribute('data-msg') ?? control.validationMessage ?? 'Enter a valid value.';
    for (const [flag, key] of KEYS) if (v[flag]) return control.getAttribute(`data-msg-${key}`) ?? fallback;
    return fallback;
}
export const checkable = c => c.internals?.willValidate ?? c.willValidate ?? true ? !c.disabled && c.type !== 'hidden' && c.type !== 'submit' && c.type !== 'button' && c.type !== 'reset' && c.localName !== 'fieldset' && c.localName !== 'pk-button' : false;
export const shouldCheck = (mode, event, showing) => (event === 'input' && (mode === 'input' || showing)) || (event === 'blur' && mode !== 'submit');

const behaviour = Base => class extends Base {
    connected() {
        if (this.$init) return;
        this.$init = true;
        this.watchSlot('', () => { const f = this.form_(); if (f) f.noValidate = true; });
        this.addEventListener('submit', e => this.submit(e));
        this.addEventListener('focusout', e => this.live(e, 'blur'));
        this.addEventListener('input', e => this.live(e, 'input'));
        this.addEventListener('reset', e => this.reset(e));
        const f = this.form_(); if (f) f.noValidate = true;
    }
    disconnected() { clearTimeout(this.$rt); }
    form_() { return this.slotted().find(e => e.localName === 'form') ?? this.querySelector('form'); }
    controls() { const f = this.form_(); return f ? Array.from(f.elements).filter(checkable) : []; }
    show(control, message) {
        const field = control.closest('pk-field');
        if (field) field.error = message;
        else if ('invalid' in control) control.invalid = Boolean(message);
        else if (message) control.setAttribute('aria-invalid', 'true'); else control.removeAttribute('aria-invalid');
        if (!message && this.showValid && 'valid' in control) control.valid = String(control.value ?? '') !== '';
    }
    check(control) { const m = messageFor(control); this.show(control, m); return !m; }
    live(e, kind) {
        const c = e.target.closest?.('pk-input, pk-textarea, pk-select, pk-checkbox, pk-combobox, pk-tag-input, pk-otp-input, pk-range, pk-colour-input, pk-unit-input, pk-dropzone, pk-radio-group, pk-switch, input, select, textarea');
        if (!c || !this.controls().includes(c)) return;
        const showing = Boolean(c.closest('pk-field')?.error);
        if (shouldCheck(this.validate, kind, showing)) queueMicrotask(() => this.check(c));
    }
    submit(e) {
        const invalid = this.controls().filter(c => !this.check(c));
        this.summarise(invalid);
        if (!invalid.length) { this.emit('pk-valid', null); return; }
        e.preventDefault();
        invalid[0].focus();
        this.emit('pk-invalid', { count: invalid.length, controls: invalid, messages: invalid.map(messageFor) });
    }
    summarise(invalid) {
        const box = this.part('summary'); const list = this.part('summary-list');
        list.replaceChildren();
        box.hidden = !this.summary || invalid.length === 0;
        for (const c of invalid) {
            const li = document.createElement('li'); const a = document.createElement('a');
            a.textContent = messageFor(c); a.setAttribute('role', 'link'); a.tabIndex = 0;
            a.addEventListener('click', () => c.focus());
            a.addEventListener('keydown', ev => { if (ev.key === 'Enter') c.focus(); });
            li.append(a); list.append(li);
        }
    }
    reset(e) { for (const c of this.controls()) this.show(c, ''); this.summarise([]); if (e) { clearTimeout(this.$rt); this.$rt = setTimeout(() => { if (!e.defaultPrevented) this.emit('pk-reset', null, { cancelable: false }); }, 0); } }
    validateAll() { const invalid = this.controls().filter(c => !this.check(c)); this.summarise(invalid); return invalid.length === 0; }
};
export default define(class extends behaviour(PkElement) {
    static tag = "pk-form";
    static props = {"validate":{"type":"enum","default":"blur","values":["blur","input","submit"],"reflect":true},"showValid":{"type":"boolean","default":false,"reflect":true},"summary":{"type":"boolean","default":false,"reflect":true}};
    static delegatesFocus = true;
    static formAssociated = false;
    static template = "<div part=\"summary\" class=\"sum\" role=\"alert\" hidden><p part=\"summary-title\" class=\"st\"><slot name=\"summary-title\">Fix these before saving</slot></p><ul part=\"summary-list\" class=\"sl\"></ul></div><slot></slot>";
    static css = ":host { display: block; }\n.sum { margin: 0 0 var(--space-4); padding: var(--space-3) var(--space-4); border: 1px solid var(--field-error); border-inline-start-width: 4px; border-radius: var(--radius-sm); background: var(--pk-form-summary-bg, var(--color-surface-alt)); }\n.st { margin: 0 0 var(--space-2); font-size: var(--text-read); font-weight: 600; }\n.sl { margin: 0; padding-inline-start: var(--space-5); }\n.sl a { color: var(--field-error); cursor: pointer; }\n";
});
