// GENERATED by tools/build.mjs from elements/timeline/: do not edit.
import { PkElement, define } from '../../js/element.js';
const behaviour = Base => class extends Base {
    connected() { this.aria({ role: 'list' }); }
    updated() { this.aria({ ariaLabel: this.label || null }); }
};
export default define(class extends behaviour(PkElement) {
    static tag = "pk-timeline";
    static props = {"label":{"type":"string","default":"","reflect":false}};
    static delegatesFocus = false;
    static formAssociated = false;
    static template = "<slot></slot>";
    static css = ":host { display: block; }\n";
});
