// GENERATED by tools/build.mjs from elements/list-group/: do not edit.
import { PkElement, define } from '../../js/element.js';
const behaviour = Base => class extends Base {
    connected() { this.aria({ role: 'list' }); this.watchSlot('', () => this.requestUpdate()); }
    updated() {
        this.aria({ ariaLabel: this.label || null });
        for (const row of this.slotted()) if (!row.hasAttribute('role')) row.setAttribute('role', 'listitem');
    }
};
export default define(class extends behaviour(PkElement) {
    static tag = "pk-list-group";
    static props = {"variant":{"type":"enum","default":"plain","values":["plain","action","flush"],"reflect":true},"checklist":{"type":"boolean","default":false,"reflect":true},"label":{"type":"string","default":"","reflect":false}};
    static delegatesFocus = false;
    static formAssociated = false;
    static template = "<slot></slot>";
    static css = ":host { display: block; overflow: hidden; border: 1px solid var(--color-border); border-radius: var(--radius-md); background: var(--color-panel); }\n:host([variant=\"flush\"]) { border-inline: 0; border-radius: 0; }\n::slotted(*) { display: flex; align-items: center; justify-content: space-between; gap: var(--space-3); box-sizing: border-box; inline-size: 100%; margin: 0; padding: var(--pad-cell); padding-inline: var(--space-4); border: 0; border-block-start: 1px solid var(--color-border); background: none; color: inherit; font: inherit; text-align: start; text-decoration: none; }\n::slotted(:first-child) { border-block-start: 0; }\n:host([variant=\"action\"]) ::slotted(a), :host([variant=\"action\"]) ::slotted(button) { min-block-size: var(--touch-target); cursor: pointer; }\n:host([variant=\"action\"]) ::slotted(a:hover), :host([variant=\"action\"]) ::slotted(button:hover) { background: var(--color-surface-alt); }\n:host([variant=\"action\"]) ::slotted([aria-current]), :host([variant=\"action\"]) ::slotted(.active) { background: color-mix(in srgb, var(--color-accent) 14%, transparent); }\n:host([variant=\"action\"]) ::slotted([disabled]) { opacity: 0.55; pointer-events: none; }\n:host([checklist]) ::slotted(label) { justify-content: flex-start; min-block-size: var(--touch-target); cursor: pointer; }\n";
});
