// The gallery as it ships in dist/gallery: the source files from site/gallery with their paths resolved for the dist layout, so the
// folder works wherever dist/ is copied or served from. Pure: the build passes in a reader and the generated data file's text.
import fs from 'node:fs';
import path from 'node:path';

// Files copied as they are, plus the rewritten ones. standalone.js and index.html are the SDK site's own host page and stay out.
const COPY = ['gallery.js', 'settings.js', 'frame.js', 'frame-boot.js', 'frame.css', 'gallery.css', 'gallery.static.js', 'elements-view.js', 'sample-tree.js', 'embed.js'];

// The dist layout puts js/, plainkit.css and icons.svg one level above the gallery folder, not two: drop one "../" from a specifier that
// climbs out of the folder. depth is how many folders deep the file sits inside the gallery folder.
export const relocate = (text, depth = 0) => text.replace(new RegExp(String.raw`(['"\`])((?:\.\./){${depth + 2},})`, 'g'), (_m, q, ups) => q + ups.slice(3));

const paths = `// GENERATED by tools/build.mjs: where the gallery finds the SDK's files, relative to this folder (the dist layout).

export const ROOT = new URL('../', import.meta.url).href;

// Stylesheets a sample frame loads, in order.
export const PAGE_CSS = ['../plainkit.css', '../plainkit-compat.css'];

export const TOKENS_CSS = 'tokens.css';
export const UTILITIES_CSS = '../components/utilities/utilities.css';
export const SPACING_CSS = '../components/spacing/spacing.css';
export const ICONS = '../icons.svg';

// The SDK site pages (theme editor, scorecard, files) are not part of dist.
export const HAS_SITE = false;

// Where the full-page templates live, relative to this folder.
export const TEMPLATES_DIR = 'templates/';
`;

export function galleryDist(read, root, dataText) {
    const dir = path.join(root, 'site', 'gallery');
    const files = new Map();
    for (const f of COPY) files.set(f, relocate(read(path.join(dir, f))));
    files.set('gallery.data.js', dataText);
    files.set('paths.js', paths);
    files.set('boots/code-explorer.js', relocate(read(path.join(dir, 'boots', 'code-explorer.js')), 1));
    files.set('embed.html', read(path.join(dir, 'embed.html')).replace('href="../../plainkit.css">', 'href="../plainkit.css">\n<link rel="stylesheet" href="../plainkit-compat.css">').replace('href="../site.css"', 'href="site.css"'));
    // The full-page templates sit at the same depth under dist/gallery/templates as under samples/templates, so their relative paths hold;
    // they only need the compat stylesheet added and the toast module's dist name.
    const tdir = path.join(root, 'samples', 'templates');
    for (const f of fs.readdirSync(tdir, { recursive: true }).map(x => x.replaceAll('\\', '/')).filter(x => /\.(html|js)$/.test(x)).sort()) {
        files.set(`templates/${f}`, read(path.join(tdir, f))
            .replace('href="../../../plainkit.css">', 'href="../../../plainkit.css">\n<link rel="stylesheet" href="../../../plainkit-compat.css">')
            .replace('../../../elements/toast-stack/toast-stack.element.js', '../../../elements/toast-stack.js'));
    }
    files.set('site.css', read(path.join(root, 'site', 'site.css')));
    files.set('tokens.css', read(path.join(root, 'tokens', 'tokens.css')));
    return files;
}
