// The gallery as it ships in dist/gallery: the source files from site/gallery with their paths resolved for the dist layout, so the
// folder works wherever dist/ is copied or served from. Pure: the build passes in a reader and the generated data file's text.
import fs from 'node:fs';
import path from 'node:path';

// Files copied as they are, plus the rewritten ones. standalone.js and index.html are the SDK site's own host page and stay out.
const COPY = ['gallery.js', 'settings.js', 'frame.js', 'frame-boot.js', 'frame.css', 'gallery.css', 'gallery.static.js', 'elements-view.js', 'sample-tree.js', 'embed.js', 'preview.js', 'pattern-mount.js'];

// The dist layout puts js/, plainkit.css and icons.svg one level above the gallery folder, not two: drop one "../" from a specifier that
// climbs out of the folder. depth is how many folders deep the file sits inside the gallery folder.
export const relocate = (text, depth = 0) => text.replace(new RegExp(String.raw`(['"\`])((?:\.\./){${depth + 2},})`, 'g'), (_m, q, ups) => q + ups.slice(3));

const paths = `// GENERATED by tools/build.mjs: where the gallery finds the SDK's files, relative to this folder (the dist layout).

export const ROOT = new URL('../', import.meta.url).href;

// Stylesheets a sample frame loads, in order.
export const PAGE_CSS = ['../plainkit.css'];

export const TOKENS_CSS = 'tokens.css';
export const UTILITIES_CSS = 'utilities.css';
export const SPACING_CSS = 'spacing.css';
export const ICONS = '../icons.svg';

// The SDK site pages (theme editor, scorecard, files) are not part of dist.
export const HAS_SITE = false;

// Where the full-page templates live, relative to this folder.
export const TEMPLATES_DIR = 'templates/';

// Where a pattern's optional script lives, relative to this folder.
export const PATTERNS_DIR = 'patterns/';

// The page that hosts a pattern or layout fragment as a whole page.
export const PREVIEW = 'preview.html';
`;

export function galleryDist(read, root, dataText, chunks = []) {
    const dir = path.join(root, 'site', 'gallery');
    const files = new Map();
    for (const f of COPY) files.set(f, relocate(read(path.join(dir, f))));
    files.set('gallery.data.js', dataText);
    for (const [f, text] of chunks) files.set(f, text); // the per-element data modules (elements/<name>.data.js), no imports to rewrite
    files.set('paths.js', paths);
    files.set('boots/code-explorer.js', relocate(read(path.join(dir, 'boots', 'code-explorer.js')), 1)); // -> ../../modules/code-explorer/: the modules unit next to the runtime
    // The gallery's own chrome and pages are pk-* elements, so the embed page needs only the page layer.
    files.set('embed.html', read(path.join(dir, 'embed.html')).replace('href="../../plainkit.css">', 'href="../plainkit.css">').replace('href="../site.css"', 'href="site.css"'));
    // The preview host (patterns and layouts as a whole page) loads the same stylesheet as the embed page.
    files.set('preview.html', read(path.join(dir, 'preview.html')).replace('href="../../plainkit.css">', 'href="../plainkit.css">'));
    // The full-page templates sit at the same depth under dist/gallery/templates as under samples/templates, so their relative paths hold;
    // they only need the toast module's dist name.
    const tdir = path.join(root, 'samples', 'templates');
    for (const f of fs.readdirSync(tdir, { recursive: true }).map(x => x.replaceAll('\\', '/')).filter(x => /\.(html|js|css)$/.test(x)).sort()) {
        files.set(`templates/${f}`, read(path.join(tdir, f))
            .replace('../../../elements/toast-stack/toast-stack.element.js', '../../../elements/toast-stack.js')
            .replace('../../site/gallery/preview.html', '../preview.html'));
    }
    // A pattern's optional script (samples/patterns/<id>/<id>.js) is loaded by preview.js from patterns/<id>/<id>.js, at the same depth as the source.
    const pdir = path.join(root, 'samples', 'patterns');
    for (const f of fs.readdirSync(pdir, { recursive: true }).map(x => x.replaceAll('\\', '/')).filter(x => /\.js$/.test(x)).sort()) files.set(`patterns/${f}`, read(path.join(pdir, f)));
    files.set('site.css', read(path.join(root, 'site', 'site.css')));
    files.set('tokens.css', read(path.join(root, 'tokens', 'tokens.css')));
    // The Foundations pages list the utility and spacing classes from their source files.
    for (const n of ['utilities', 'spacing']) files.set(`${n}.css`, read(path.join(root, 'base', `${n}.css`)));
    return files;
}
