// The Guides' content, read at build time: every site/guides/content/<id>.md (front matter: title, order, summary) is converted by tools/markdown.mjs into the
// generated module site/guides/guides.data.js, which the Guides page imports. The file name is the guide's id and its address (#/<id>), so it must be lowercase
// letters, digits and dashes. A guide links to another one with a plain relative link, `[Theming](theming.md)` or `[a heading](theming.md#dark-and-light)`;
// the build checks the guide and the heading exist. Any problem (front matter, links, images, headings) fails the build with the file it is in.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { markdownToHtml, parseFrontMatter } from './markdown.mjs';
import { guideWords } from '../site/guides/guides-search.js';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
export const GUIDES_DIR = path.join(root, 'site', 'guides', 'content');

/** { guides: [{ id, title, order, summary, headings: [{ level, id, text }], html, words }] ordered by `order`, problems: ['<file>: <what>'] }.
 * `words` is the guide's full-text search index (site/guides/guides-search.js: title, summary and the body's plain text, as a small deduplicated,
 * space-separated word list, one line). */
export function loadGuides(dir = GUIDES_DIR) {
    const problems = [], found = [];
    const files = fs.existsSync(dir) ? fs.readdirSync(dir).filter(f => f.endsWith('.md')).sort() : [];
    const ids = new Set(files.map(f => f.slice(0, -3)));
    const links = []; // [file, target id, heading id or null]: checked once every guide has its headings
    for (const file of files) {
        const id = file.slice(0, -3), fail = msg => problems.push(`${file}: ${msg}`);
        if (!/^[a-z0-9]+(-[a-z0-9]+)*$/.test(id)) fail('the file name is the guide\'s address: lowercase letters, digits and dashes');
        const { data, body } = parseFrontMatter(fs.readFileSync(path.join(dir, file), 'utf8'));
        for (const key of ['title', 'order', 'summary']) if (!data[key]) fail(`front matter needs ${key}`);
        if (data.order && !/^\d+$/.test(data.order)) fail(`order must be a whole number, not "${data.order}"`);
        const linkFor = href => {
            const [name, frag] = href.split('#');
            if (!ids.has(name.slice(0, -3))) return null;
            links.push([file, name.slice(0, -3), frag ?? null]);
            return `#/${name.slice(0, -3)}${frag ? `/${frag}` : ''}`;
        };
        const imageFor = src => (!/^[a-z]+:|^\/|\.\./i.test(src) && fs.existsSync(path.join(dir, src)) ? `content/${src}` : null); // local files under content/ only
        const r = markdownToHtml(body, { linkFor, imageFor });
        for (const p of r.problems) fail(p);
        const title = data.title ?? id, summary = data.summary ?? '';
        // A space-separated string, not an array: JSON.stringify(guides, null, 4) below would otherwise put every word on its own line, and the carveout
        // test's per-line "no repository path" check (tests/carveout.test.mjs) would then miss the surrounding Blazor guide text that makes a folder
        // name mentioned in it legitimate content instead of a leaked path.
        found.push({ id, title, order: Number(data.order ?? 0), summary, headings: r.headings, html: r.html, words: guideWords(title, summary, r.html).join(' ') });
    }
    for (const [file, to, frag] of links) if (frag && !found.find(g => g.id === to)?.headings.some(h => h.id === frag)) problems.push(`${file}: ${to}.md has no heading "${frag}"`);
    const orders = found.map(g => g.order);
    for (const g of found) if (orders.filter(o => o === g.order).length > 1) problems.push(`${g.id}.md: order ${g.order} is used by another guide`);
    return { guides: found.sort((a, b) => a.order - b.order || a.id.localeCompare(b.id)), problems };
}

/** The text of site/guides/guides.data.js. Throws with every problem when the content is not valid, so the build stops on it. */
export function guidesModule(dir = GUIDES_DIR) {
    const { guides, problems } = loadGuides(dir);
    if (problems.length) throw new Error(`site/guides/content: ${problems.length} problem(s)\n- ${problems.join('\n- ')}`);
    return `// GENERATED by tools/build.mjs from site/guides/content/*.md: do not edit. Edit the Markdown and run the build.\n// One entry per guide, ordered: its address (id), title, summary, headings (for the page's own checks), the sanitised HTML the page inserts, and words\n// (its full-text search index, guides-search.js).\nexport const GUIDES = ${JSON.stringify(guides, null, 4)};\n`;
}
