// GENERATED by tools/build.mjs from elements/tooltip/: do not edit.
import { PkElement, define } from '../../js/element.js';
import { place } from '../../js/positioning.js';

export const DEFAULT_DELAY = 400;
export const LONG_PRESS = 500;

export function showDelay(kind, configured = DEFAULT_DELAY) {
    if (kind === 'focus') return 0;
    if (kind === 'touch') return LONG_PRESS;
    return Number.isFinite(configured) && configured >= 0 ? configured : DEFAULT_DELAY;
}

const ids = { n: 0 };
const behaviour = Base => class extends Base {
    connected() {
        if (!this.$w) {
            this.$w = true;
            const on = (t, f) => this.addEventListener(t, f);
            on('pointerover', e => { if (e.pointerType === 'mouse') this.schedule('hover'); });
            on('pointerout', e => { if (this.contains(e.relatedTarget)) return; if (this.interactive && e.pointerType === 'mouse') { clearTimeout(this.$t); this.$t = setTimeout(() => { if (!this.matches(':hover')) this.hide(); }, 150); } else this.hide(); });
            on('focusin', () => { if (!this.$down) this.schedule('focus'); });
            on('focusout', e => { if (this.interactive && (this.contains(e.relatedTarget) || this.shadowRoot.contains(e.relatedTarget))) return; this.hide(); });
            on('pointerdown', e => { this.$down = true; if (this.interactive && e.pointerType === 'touch') { if (e.composedPath().includes(this.part('tip'))) return; if (this.shown) this.hide(); else this.show(); return; } if (this.interactive && this.shown && e.composedPath().includes(this.part('tip'))) return; if (e.pointerType === 'touch') this.schedule('touch'); else this.hide(); });
            const up = () => { this.$down = false; if (!this.shown) clearTimeout(this.$t); };
            on('pointerup', up); on('pointercancel', up);
            on('keydown', e => { if (e.key === 'Escape') this.hide(); });
            this.$hide = () => this.hide();
            this.watchSlot('content', () => { if (this.shown) place(this, this.part('tip'), { placement: this.placement, offset: 6 }); });
        }
        this.describe();
    }
    disconnected() { clearTimeout(this.$t); this.hide(); }
    changed(name) { if (name === 'text') this.describe(); }
    describe() {
        if (this.help) return;
        const target = this.slotted()[0];
        if (!target || !this.text) return;
        if (!this.$d || !this.$d.isConnected) { this.$d = document.createElement('span'); this.$d.hidden = true; this.$d.id = `pk-tip-${++ids.n}`; this.append(this.$d); }
        this.$d.textContent = this.text;
        target.setAttribute('aria-describedby', this.$d.id);
    }
    schedule(kind) { clearTimeout(this.$t); this.$t = setTimeout(() => this.show(), showDelay(kind, this.delay)); }
    show() {
        if (this.shown || (!this.text && !this.slotted('content').length)) return;
        this.shown = true;
        place(this, this.part('tip'), { placement: this.placement, offset: 6 });
        addEventListener('scroll', this.$hide, true);
        this.emit('pk-show', null);
    }
    hide() {
        clearTimeout(this.$t);
        if (!this.shown) return;
        this.shown = false;
        removeEventListener('scroll', this.$hide, true);
        this.emit('pk-hide', null);
    }
};
export default define(class extends behaviour(PkElement) {
    static tag = "pk-tooltip";
    static props = {"text":{"type":"string","default":"","reflect":true},"placement":{"type":"string","default":"top","reflect":true},"delay":{"type":"number","default":400,"reflect":true},"shown":{"type":"boolean","default":false,"reflect":true},"interactive":{"type":"boolean","default":false,"reflect":true},"help":{"type":"boolean","default":false,"reflect":true},"enrich":{"type":"boolean","default":false,"reflect":true},"heading":{"type":"string","default":"","reflect":true},"label":{"type":"string","default":"Help","reflect":true}};
    static delegatesFocus = false;
    static formAssociated = false;
    static template = "<button type=\"button\" part=\"help\" data-if=\"help\" aria-label=\"{{label}}\">ⓘ</button><span part=\"target\"><slot></slot></span><div part=\"tip\" role=\"tooltip\"><strong part=\"heading\" data-if=\"heading\">{{heading}}</strong><div part=\"body\"><slot name=\"content\">{{text}}</slot></div><div part=\"links\"><slot name=\"links\"></slot></div></div>";
    static css = "/* pk-tooltip: inverted so it reads in both themes (text colour as ground, page colour as ink). Placed by the positioning helper. */\n:host { display: inline-block; }\n\n[part=\"tip\"] {\n    display: none;\n    position: fixed;\n    top: 0;\n    left: 0;\n    z-index: var(--z-tip);\n    max-width: var(--pk-tooltip-max-w, min(20rem, calc(100vw - 2 * var(--space-4))));\n    padding: var(--space-1) var(--space-2);\n    border-radius: var(--radius-sm);\n    background: var(--color-text);\n    color: var(--color-bg);\n    font-size: var(--text-read);\n    line-height: 1.35;\n    overflow-wrap: anywhere;\n    pointer-events: none;\n    box-shadow: var(--shadow-pop);\n}\n\n:host([shown]) [part=\"tip\"] { display: block; }\n\n:host([interactive]) [part=\"tip\"] { pointer-events: auto; }\n\n[part=\"heading\"] { display: block; margin-bottom: var(--space-1); }\n\n[part=\"links\"] { display: flex; flex-wrap: wrap; gap: var(--space-3); }\n\n[part=\"links\"]:not(:has(::slotted(*))) { display: none; }\n\n::slotted([slot=\"links\"]) { color: inherit; text-decoration: underline; }\n\n[part=\"help\"] { display: inline-flex; align-items: center; justify-content: center; min-width: 1.25rem; min-height: 1.25rem; padding: 0; margin-inline-end: var(--space-1); border: 0; border-radius: var(--radius-round); background: transparent; color: var(--color-muted); font: inherit; cursor: help; }\n\n[part=\"help\"]:hover { color: var(--color-text); }\n\n[part=\"help\"]:focus-visible { outline: var(--focus-ring); outline-offset: 2px; }\n\n:host([enrich]) [part=\"target\"] { border-bottom: 1px dotted var(--color-muted); cursor: help; }\n\n@media (max-width: 640px) { [part=\"help\"] { min-width: var(--touch-target); min-height: var(--touch-target); margin: calc(-1 * var(--space-3)) 0; } }\n";
});
