// GENERATED by tools/build.mjs from elements/skip-link/: do not edit.
import { PkElement, define } from '../../js/element.js';
import { skipTarget } from '../../js/scroll-aids.js';

const behaviour = Base => class extends Base {
    updated() { const t = skipTarget(this.href); const a = this.part('link'); if (t) a.setAttribute('href', `#${t}`); else a.removeAttribute('href'); }
    connected() {
        if (this.$w) return;
        this.$w = true;
        this.part('link').addEventListener('click', e => {
            const id = skipTarget(this.href); const t = id && document.getElementById(id);
            if (!t) return;
            e.preventDefault();
            if (!t.hasAttribute('tabindex')) t.setAttribute('tabindex', '-1');
            t.focus(); t.scrollIntoView();
        });
    }
};
export default define(class extends behaviour(PkElement) {
    static tag = "pk-skip-link";
    static props = {"href":{"type":"string","default":"#main","reflect":true}};
    static delegatesFocus = false;
    static formAssociated = false;
    static template = "<a part=\"link\"><slot>Skip to content</slot></a>";
    static css = "/* pk-skip-link: off-screen until it takes focus, then a visible button at the top-start corner. */\n:host { position: fixed; inset-block-start: var(--space-2); inset-inline-start: var(--space-2); z-index: var(--z-skip); }\n\n[part=\"link\"] { position: absolute; clip-path: inset(50%); width: 1px; height: 1px; overflow: hidden; }\n\n[part=\"link\"]:focus { position: static; clip-path: none; width: auto; height: auto; display: inline-flex; align-items: center; min-height: var(--touch-target); padding: var(--space-1) var(--space-4); border-radius: var(--radius-md); background: var(--color-accent); color: var(--btn-primary-fg); font-size: var(--text-read); font-weight: 600; text-decoration: none; box-shadow: var(--shadow-pop); outline: var(--focus-ring); outline-offset: 2px; }\n";
});
