// GENERATED by tools/build.mjs from elements/accordion-item/: do not edit.
import { PkElement, define } from '../../js/element.js';
const behaviour = Base => class extends Base {
    connected() {
        if (this.$t) return;
        this.$t = () => { const open = this.part('details').open; if (open !== this.open) { this.open = open; this.emit('pk-toggle', { open }); } };
        this.part('details').addEventListener('toggle', this.$t);
    }
    updated() { const d = this.part('details'); if (d.open !== this.open) d.open = this.open; }
};
export default define(class extends behaviour(PkElement) {
    static tag = "pk-accordion-item";
    static props = {"heading":{"type":"string","default":"","reflect":false},"open":{"type":"boolean","default":false,"reflect":true}};
    static delegatesFocus = false;
    static formAssociated = false;
    static template = "<details part=\"details\"><summary part=\"summary\"><slot name=\"icon\"></slot><span part=\"heading\"><slot name=\"heading\">{{heading}}</slot></span><span part=\"chevron\" aria-hidden=\"true\"></span></summary><div part=\"panel\"><slot></slot></div></details>";
    static css = ":host { display: block; border: 1px solid var(--color-border); border-radius: var(--radius-md); background: var(--color-panel); }\ndetails { interpolate-size: allow-keywords; }\ndetails::details-content { block-size: 0; overflow: hidden; transition: block-size var(--pk-accordion-duration, 0.2s) ease, content-visibility var(--pk-accordion-duration, 0.2s) allow-discrete; }\ndetails[open]::details-content { block-size: auto; }\nsummary { display: flex; align-items: center; gap: var(--space-3); min-block-size: var(--touch-target); padding: var(--space-3) var(--space-4); font-weight: 600; cursor: pointer; list-style: none; }\nsummary::-webkit-details-marker { display: none; }\nsummary:focus-visible { outline: var(--focus-ring); outline-offset: -2px; }\n[part=\"heading\"] { flex: 1; }\n[part=\"chevron\"] { flex: none; inline-size: 0.5em; block-size: 0.5em; border: solid var(--color-muted); border-width: 0 2px 2px 0; transform: rotate(45deg); transition: transform var(--pk-accordion-duration, 0.2s); }\ndetails[open] [part=\"chevron\"] { transform: rotate(-135deg); }\n[part=\"panel\"] { padding: 0 var(--space-4) var(--space-4); }\n@media (prefers-reduced-motion: reduce) { details::details-content, [part=\"chevron\"] { transition: none; } }\n";
});
