// ONE command that runs what CI runs, in the same groups, so a failure reproduces locally with the same message. Node only, no dependencies.
//
//   node scripts/verify.mjs                  everything CI runs on a pull request except the browser and pack jobs (lint + node + dotnet)
//   node scripts/verify.mjs --fast           bootstrap + changelog + node tests (the inner loop)
//   node scripts/verify.mjs --no-dotnet      skip dotnet build + test
//   node scripts/verify.mjs --browser        also the in-browser element suite (node scripts/attest-browser.mjs, needs Chrome or Edge, about 3 minutes)
//   node scripts/verify.mjs --pack           also dotnet pack + node scripts/check-package.mjs
//   node scripts/verify.mjs --only node      one CI job: a group (lint, node, dotnet, browser, pack) or a check id (see --list); what it needs runs too
//   node scripts/verify.mjs --list           the checks, their groups and what each fix is
//   --base <ref>   the pull request's base (default: origin/main when it exists; CI passes GITHUB_BASE_REF). Without one the checks that compare
//                  against the base (changelog-pr, release-*) are skipped, and the output says so.
//   --verbose      print the full output of every check, not only of failed ones
//
// Each check prints one line (name, seconds, ok/FAIL/skip); a failed one adds the first useful lines of its output and a `FIX:` line. Exit code 1 when
// any check failed, 2 for a bad argument. The checks run in parallel where they are independent (the cheap ones first; everything that reads generated
// files waits for the bootstrap). The FIX messages are the table CHECKS below: AGENTS.md ("When CI fails") shows the same table, generated by
// `node scripts/verify.mjs --update-docs` and compared by scripts/tests/verify.test.mjs.
//
// Also (used by ci.yml): `--budget <group>` appends "job seconds against its budget" to the job summary; with GITHUB_OUTPUT set a failed run writes
// its failures (`failures=<json>`) for the "CI summary" job, and with GITHUB_STEP_SUMMARY set it writes a timing table.
import { spawn, spawnSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { JOBS, budgetNote } from './ci-report.mjs';
import { isGenerated } from './generated.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const NODE = process.execPath;
export const GROUPS = ['lint', 'node', 'dotnet', 'browser', 'pack'];
export const DEFAULT_GROUPS = ['lint', 'node', 'dotnet'];
export const TABLE_START = '<!-- verify-fix-table:start (generated by node scripts/verify.mjs --update-docs; do not edit by hand) -->';
export const TABLE_END = '<!-- verify-fix-table:end -->';

const NODE_TEST_ARGS = ['--test', 'core/tests/*.test.mjs', 'core/elements/*/*.test.mjs', 'core/modules/*/*.test.mjs', 'core/icons/*.test.mjs', 'scripts/tests/*.test.mjs'];

// The checks, cheap first. `needs`: checks that must have passed. `after`: checks that must have finished first when they are selected, pass or fail
// (dotnet and pack both build PlainKit.Blazor in Release, and two builds of one project in one folder lock each other's files; CI runs them in separate jobs). `fast`: part of --fast. `cmd(ctx)`: the command ([program, ...args]) or { skip: reason };
// `fn(ctx)`: an in-process check returning { ok, output } or { skip }. `cause` and `fix` are the one place the failure guidance is written.
export const CHECKS = [
    { id: 'bootstrap', group: 'setup', needs: [], fast: true, cmd: () => [NODE, 'scripts/bootstrap.mjs', '--quiet'],
        cause: 'a generator rejected a source file (the output names the script and the file)',
        fix: 'fix the source file it names, then run `node scripts/bootstrap.mjs`' },
    { id: 'changelog', group: 'lint', needs: [], fast: true, cmd: () => [NODE, 'scripts/changelog.mjs', 'check'],
        cause: 'a fragment in `changelog/unreleased/` is malformed or still has its placeholder',
        fix: 'fix the fragment the output names (format: `changelog/README.md`), then run `node scripts/changelog.mjs check`' },
    { id: 'changelog-pr', group: 'lint', needs: [], fast: true,
        cmd: ctx => (ctx.base ? [NODE, 'scripts/changelog.mjs', 'check-pr', '--base', ctx.base] : { skip: 'no base branch: pass --base <ref>' }),
        cause: 'the pull request changes more than docs and adds no changelog fragment',
        fix: 'run `node scripts/changelog.mjs new <added|changed|fixed|removed|breaking|notes> <slug> --issue N` and write the entry; a change with no visible effect gets the label `no-changelog` and the reason in the description' },
    { id: 'release-fragments', group: 'lint', needs: [], fast: true, fn: releaseFragments,
        cause: '`core/VERSION` changed (a release pull request) but changelog fragments are left',
        fix: 'run `node scripts/changelog.mjs compile --version <X.Y.Z>`' },
    { id: 'version', group: 'node', needs: ['bootstrap'], fast: false, cmd: () => [NODE, 'core/tools/versioning.mjs', 'check'],
        cause: '`core/VERSION`, `core/package.json` and the stamped files disagree',
        fix: 'run `node core/tools/versioning.mjs set <X.Y.Z>` (or restore `core/VERSION`), then `node scripts/bootstrap.mjs`' },
    { id: 'release-pr', group: 'node', needs: ['bootstrap'], fast: false, fn: releasePr,
        cause: '`core/VERSION` changed but the API baseline was not refreshed, or the version does not cover the API changes',
        fix: 'run `node core/tools/versioning.mjs bump` to see the version the API changes need, then `node core/tools/api-surface.mjs --write --release <X.Y.Z>`' },
    { id: 'generated-tree', group: 'node', needs: ['bootstrap'], fast: false, fn: generatedTree,
        cause: 'a generated file is tracked by git, or the bootstrap changed a tracked file',
        fix: 'run `git rm -r --cached <path>` for each tracked generated path (`node scripts/generated.mjs list` shows them); never commit or hand-edit generated files' },
    { id: 'node-tests', group: 'node', needs: ['bootstrap'], fast: true, cmd: () => [NODE, ...NODE_TEST_ARGS],
        cause: 'a node test failed: the change broke what the test guards',
        fix: 'run the failing file alone with `node --test <file>` (its path is in the output), fix the code, not the test; after a source change run `node scripts/bootstrap.mjs` first' },
    { id: 'dotnet', group: 'dotnet', needs: ['bootstrap'], fast: false, cmd: () => ['dotnet', 'test', 'PlainKit.slnx', '--configuration', 'Release', '--nologo'],
        cause: 'a build error, a failing test, or a generated file missing or stale',
        fix: 'run `node scripts/bootstrap.mjs`, then `dotnet test PlainKit.slnx --configuration Release` and fix the first error' },
    { id: 'browser', group: 'browser', needs: ['bootstrap'], fast: false, cmd: () => [NODE, 'scripts/attest-browser.mjs'],
        cause: 'an element case failed in a real browser (or the attestation no longer matches `report.json`)',
        fix: 'run `node scripts/attest-browser.mjs`, fix the element (never weaken the case) and commit the refreshed `core/tests/browser/report.json`; a case that passes on a rerun is flaky: note it on the issue' },
    { id: 'pack', group: 'pack', needs: ['bootstrap'], after: ['dotnet'], fast: false, fn: packCheck,
        cause: 'the package has `content/` or `contentFiles/` entries, lacks the static web assets or skills, or has the wrong version',
        fix: 'run `dotnet pack blazor/src/PlainKit.Blazor -c Release -o <dir>` then `node scripts/check-package.mjs <dir>`, and change `PlainKit.Blazor.csproj` as the message says' },
];
for (const c of CHECKS) c.name = c.id;

export const USAGE = `usage: node scripts/verify.mjs [--fast] [--no-dotnet] [--browser] [--pack] [--only <group|check>[,...]] [--base <ref>] [--verbose] [--list]
groups: ${GROUPS.join(', ')}   (node scripts/verify.mjs --list shows the checks)`;

/** Parses argv. Returns { opts, errors }. */
export function parseArgs(argv) {
    const opts = { fast: false, noDotnet: false, browser: false, pack: false, only: [], base: null, verbose: false, list: false, budget: null, fixTable: false, updateDocs: false, help: false };
    const errors = [];
    for (let i = 0; i < argv.length; i++) {
        const a = argv[i];
        const value = () => { const v = argv[i + 1]; if (v === undefined || v.startsWith('--')) { errors.push(`${a} needs a value`); return null; } i++; return v; };
        if (a === '--fast') opts.fast = true;
        else if (a === '--no-dotnet') opts.noDotnet = true;
        else if (a === '--browser') opts.browser = true;
        else if (a === '--pack') opts.pack = true;
        else if (a === '--verbose') opts.verbose = true;
        else if (a === '--list') opts.list = true;
        else if (a === '--fix-table') opts.fixTable = true;
        else if (a === '--update-docs') opts.updateDocs = true;
        else if (a === '--help' || a === '-h') opts.help = true;
        else if (a === '--only') { const v = value(); if (v) opts.only.push(...v.split(',').map(s => s.trim()).filter(Boolean)); }
        else if (a === '--base') opts.base = value();
        else if (a === '--budget') opts.budget = value();
        else errors.push(`unknown argument ${a}`);
    }
    const known = new Set([...GROUPS, ...CHECKS.map(c => c.id)]);
    for (const o of opts.only) if (!known.has(o)) errors.push(`--only ${o}: not a group or check (groups: ${GROUPS.join(', ')}; checks: ${CHECKS.map(c => c.id).join(', ')})`);
    if (opts.budget && !JOBS[opts.budget]) errors.push(`--budget ${opts.budget}: not a group (${GROUPS.join(', ')})`);
    if (opts.fast && opts.only.length) errors.push('use either --fast or --only, not both');
    return { opts, errors };
}

/** The checks to run, in table order, including what they need. Pure. */
export function selectChecks(opts, checks = CHECKS) {
    let picked;
    if (opts.only.length) picked = checks.filter(c => opts.only.includes(c.group) || opts.only.includes(c.id));
    else if (opts.fast) picked = checks.filter(c => c.fast);
    else {
        const groups = new Set(DEFAULT_GROUPS);
        if (opts.noDotnet) groups.delete('dotnet');
        if (opts.browser) groups.add('browser');
        if (opts.pack) groups.add('pack');
        picked = checks.filter(c => groups.has(c.group));
    }
    const ids = new Set(picked.map(c => c.id));
    const add = id => { if (ids.has(id)) return; ids.add(id); checks.find(c => c.id === id)?.needs.forEach(add); };
    picked.forEach(c => c.needs.forEach(add));
    return checks.filter(c => ids.has(c.id));
}

// ---------- output helpers (pure) ----------

const ANSI = /\[[0-9;]*[A-Za-z]/g;
export const stripAnsi = s => String(s).replace(ANSI, '');
export const seconds = ms => `${(ms / 1000).toFixed(1)} s`;

/** The first useful lines of a failed check's output: the "failing tests" list, else the first error-looking line with a line of context, else the start. */
export function usefulLines(text, { maxLines = 14, maxChars = 1500 } = {}) {
    const lines = stripAnsi(text).split(/\r?\n/);
    const find = re => lines.findIndex(l => re.test(l));
    let start = find(/^\s*(✖\s*)?failing tests:/i);
    if (start < 0) { const e = find(/(✖|^\s*not ok |\bFAIL(ED)?\b|\bFailed\b|\berror\s+[A-Z]+\d+|\berror:|\bError:|\bcheck-package:|\bnot right)/); if (e >= 0) start = Math.max(0, e - 1); }
    if (start < 0) start = Math.max(0, lines.findIndex(l => l.trim()));
    const out = lines.slice(start).filter(l => !/^\s+at .*(node:|node_modules)/.test(l) && l.trim() !== '').slice(0, maxLines).map(l => (l.length > 170 ? `${l.slice(0, 170)} ...` : l.trimEnd()));
    let text2 = out.join('\n').trim();
    if (text2.length > maxChars) text2 = `${text2.slice(0, maxChars)} ...`;
    return text2;
}

/** The generated "When CI fails" table (markdown), from the CHECKS table. */
export function fixTable(checks = CHECKS) {
    const cell = s => String(s).replaceAll('|', '\\|');
    return ['| Failing check | Likely cause | Fix |', '| --- | --- | --- |',
        ...checks.map(c => `| \`${c.id}\` (${c.group === 'setup' ? 'every job' : `job \`${c.group}\``}) | ${cell(c.cause)} | ${cell(c.fix)} |`)].join('\n');
}

/** AGENTS.md text with the region between the markers replaced by the current table (null when the markers are missing). */
export function withFixTable(text, checks = CHECKS) {
    const a = text.indexOf(TABLE_START), b = text.indexOf(TABLE_END);
    if (a < 0 || b < a) return null;
    return `${text.slice(0, a)}${TABLE_START}\n${fixTable(checks)}\n${text.slice(b)}`;
}

// ---------- base branch and release detection ----------

const git = (args, cwd = root) => spawnSync('git', args, { cwd, encoding: 'utf8' });

/** The base ref to compare against: --base, else the pull request's (GITHUB_BASE_REF), else origin/main when it exists locally; null in CI without one. */
export function resolveBase({ opts, env = process.env, cwd = root }) {
    if (opts.base) return opts.base;
    if (env.GITHUB_BASE_REF) return `origin/${env.GITHUB_BASE_REF}`;
    if (env.CI || env.GITHUB_ACTIONS) return null;
    return git(['rev-parse', '--verify', '--quiet', 'origin/main'], cwd).status === 0 ? 'origin/main' : null;
}

/** True when core/VERSION differs from the base's (and the base had one): a release pull request. */
export function isReleasePr(base, cwd = root) {
    if (!base) return false;
    if (git(['cat-file', '-e', `${base}:core/VERSION`], cwd).status !== 0) return false;
    return git(['diff', '--quiet', base, '--', 'core/VERSION'], cwd).status !== 0;
}

// ---------- in-process checks ----------

async function releaseFragments(ctx) {
    if (!ctx.base) return { skip: 'no base branch: pass --base <ref>' };
    if (!isReleasePr(ctx.base, ctx.root)) return { ok: true, output: 'not a release pull request' };
    const dir = path.join(ctx.root, 'changelog', 'unreleased');
    const left = fs.existsSync(dir) ? fs.readdirSync(dir).filter(f => f !== '.gitkeep') : [];
    return left.length ? { ok: false, output: `core/VERSION changed (a release pull request) but fragments are left:\n${left.join('\n')}` } : { ok: true, output: 'release pull request: no fragments left' };
}

async function releasePr(ctx) {
    if (!ctx.base) return { skip: 'no base branch: pass --base <ref>' };
    const show = git(['show', `${ctx.base}:core/site/scorecard/api.baseline.json`], ctx.root);
    if (show.status !== 0) return { skip: `${ctx.base} has no API baseline` };
    const baseline = path.join(fs.mkdtempSync(path.join(os.tmpdir(), 'pk-baseline-')), 'base-baseline.json');
    fs.writeFileSync(baseline, show.stdout);
    let output = '';
    const step = async args => { const r = await runCmd([NODE, ...args], ctx.root); output += `$ node ${args.join(' ')}\n${r.out}`; return r.code === 0; };
    if (isReleasePr(ctx.base, ctx.root)) {
        output += 'core/VERSION changed: this is a release pull request\n';
        const a = await step(['core/tools/versioning.mjs', 'check', '--release']);
        const b = await step(['core/tools/versioning.mjs', 'bump', '--baseline', baseline, '--require']);
        return { ok: a && b, output };
    }
    output += 'core/VERSION unchanged: not a release pull request (information only)\n';
    return { ok: await step(['core/tools/versioning.mjs', 'bump', '--baseline', baseline]), output };
}

// CI runs `node scripts/generated.mjs check`. On a machine with uncommitted edits that command always fails ("the bootstrap changed tracked files"),
// so there the check compares against the state before the bootstrap instead.
async function generatedTree(ctx) {
    if (!ctx.dirtyBefore.length) {
        const r = await runCmd([NODE, 'scripts/generated.mjs', 'check'], ctx.root);
        return { ok: r.code === 0, output: r.out };
    }
    const problems = [];
    const tracked = git(['ls-files'], ctx.root).stdout.split('\n').filter(Boolean).filter(isGenerated);
    if (tracked.length) problems.push(`${tracked.length} generated file(s) are tracked by git (first: ${tracked[0]})`);
    const now = git(['status', '--porcelain', '--untracked-files=no'], ctx.root).stdout.split('\n').filter(Boolean);
    const before = new Set(ctx.dirtyBefore);
    const changed = now.filter(l => !before.has(l));
    if (changed.length) problems.push(`the bootstrap changed ${changed.length} tracked file(s) (first: ${changed[0].trim()})`);
    return problems.length ? { ok: false, output: `Bootstrap does not leave the tree clean:\n- ${problems.join('\n- ')}` }
        : { ok: true, output: 'no generated path is tracked; the bootstrap changed nothing (your uncommitted edits were there before it ran)' };
}

async function packCheck(ctx) {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'pk-pack-'));
    try {
        const p = await runCmd(['dotnet', 'pack', 'blazor/src/PlainKit.Blazor', '-c', 'Release', '-o', dir, '--nologo'], ctx.root);
        if (p.code !== 0) return { ok: false, output: p.out };
        const c = await runCmd([NODE, 'scripts/check-package.mjs', dir], ctx.root);
        return { ok: c.code === 0, output: c.out };
    } finally { fs.rmSync(dir, { recursive: true, force: true }); }
}

// ---------- running ----------

/** Runs a command, resolves { code, out } with stdout and stderr interleaved as they arrived. Never rejects. */
export function runCmd(cmd, cwd = root, env = process.env) {
    return new Promise(resolve => {
        let out = '';
        let child;
        try { child = spawn(cmd[0], cmd.slice(1), { cwd, env, windowsHide: true }); } catch (e) { resolve({ code: 127, out: `${e.message}\n` }); return; }
        child.stdout.on('data', d => { out += d; });
        child.stderr.on('data', d => { out += d; });
        child.on('error', e => { out += `${e.message}\n`; resolve({ code: 127, out }); });
        child.on('close', code => resolve({ code: code ?? 1, out }));
    });
}

async function runOne(check, ctx) {
    const t = performance.now();
    try {
        if (check.fn) {
            const r = await check.fn(ctx);
            if (r.skip) return { status: 'skip', ms: performance.now() - t, reason: r.skip, out: '' };
            return { status: r.ok ? 'ok' : 'FAIL', ms: performance.now() - t, out: r.output ?? '' };
        }
        const cmd = check.cmd(ctx);
        if (!Array.isArray(cmd)) return { status: 'skip', ms: performance.now() - t, reason: cmd.skip, out: '' };
        const r = await runCmd(cmd, ctx.root);
        return { status: r.code === 0 ? 'ok' : 'FAIL', ms: performance.now() - t, out: r.out };
    } catch (e) { return { status: 'FAIL', ms: performance.now() - t, out: `${e.stack || e}` }; }
}

/** Runs the selected checks in parallel, each after the checks it needs. `onDone(check, result)` is called as each finishes. Returns the results in table order. */
export async function runChecks(selected, ctx, onDone = () => {}) {
    const started = new Map();
    const start = check => {
        if (started.has(check.id)) return started.get(check.id);
        const p = (async () => {
            const pick = id => selected.find(c => c.id === id);
            const deps = await Promise.all(check.needs.filter(pick).map(id => start(pick(id))));
            await Promise.all((check.after ?? []).filter(pick).map(id => start(pick(id))));
            const blocked = deps.find(d => d.status !== 'ok');
            const result = blocked ? { status: 'skip', ms: 0, reason: 'a check it needs failed', out: '' } : await runOne(check, ctx);
            result.check = check;
            onDone(check, result);
            return result;
        })();
        started.set(check.id, p);
        return p;
    };
    return Promise.all(selected.map(start));
}

export function formatResult(check, r, { verbose = false, ci = false } = {}) {
    const pad = check.id.padEnd(18);
    if (r.status === 'skip') return `skip  ${pad} ${r.reason}`;
    const lines = [`${r.status === 'ok' ? 'ok   ' : 'FAIL '} ${pad} ${seconds(r.ms)}`];
    if (r.status === 'FAIL') {
        const ex = usefulLines(r.out);
        if (ex) lines.push(...ex.split('\n').map(l => `      ${l}`));
        lines.push(`FIX: ${check.fix}`);
        if (ci) lines.push(`::group::full output of ${check.id}`, stripAnsi(r.out).trimEnd(), '::endgroup::');
    } else if (verbose && r.out.trim()) lines.push(...stripAnsi(r.out).trimEnd().split('\n').map(l => `      ${l}`));
    return lines.join('\n');
}

/** The failures for the CI summary job: [{ id, name, fix, excerpt }]. */
export const failuresOf = results => results.filter(r => r.status === 'FAIL').map(r => ({ id: r.check.id, name: r.check.name, fix: r.check.fix, excerpt: usefulLines(r.out, { maxChars: 900 }) }));

const escapeAnnotation = s => String(s).replace(/%/g, '%25').replace(/\r/g, '%0D').replace(/\n/g, '%0A');

function writeCiFiles(results, totalMs, label, env = process.env) {
    const failures = failuresOf(results);
    if (env.GITHUB_OUTPUT && failures.length) fs.appendFileSync(env.GITHUB_OUTPUT, `failures=${JSON.stringify(failures)}\n`);
    for (const f of failures) if (env.GITHUB_ACTIONS) console.log(`::error title=${escapeAnnotation(`verify ${f.name} failed`)}::${escapeAnnotation(f.fix)}`);
    if (env.GITHUB_STEP_SUMMARY) {
        const rows = results.map(r => `| ${r.check.id} | ${r.status === 'skip' ? `skip: ${r.reason}` : r.status} | ${r.status === 'skip' ? '' : seconds(r.ms)} |`);
        fs.appendFileSync(env.GITHUB_STEP_SUMMARY, `#### ${label}\n\n| Check | Result | Time |\n| --- | --- | --- |\n${rows.join('\n')}\n\nTotal ${seconds(totalMs)}.\n\n`);
    }
}

export async function main(argv, env = process.env) {
    const { opts, errors } = parseArgs(argv);
    if (opts.help) { console.log(USAGE); return 0; }
    if (errors.length) { console.error(`verify: ${errors.join('\nverify: ')}\n${USAGE}`); return 2; }
    if (opts.list) { for (const c of CHECKS) console.log(`${c.id.padEnd(18)} ${String(c.group).padEnd(8)} ${c.fast ? 'fast ' : '     '} ${c.fix}`); return 0; }
    if (opts.fixTable) { console.log(fixTable()); return 0; }
    if (opts.updateDocs) {
        const file = path.join(root, 'AGENTS.md');
        const next = withFixTable(fs.readFileSync(file, 'utf8'));
        if (next === null) { console.error(`verify: AGENTS.md has no ${TABLE_START} ... ${TABLE_END} region`); return 1; }
        fs.writeFileSync(file, next);
        console.log('AGENTS.md: the "When CI fails" table is current');
        return 0;
    }
    if (opts.budget) {
        const t0 = Number(env.PK_JOB_START);
        if (!t0) { console.error('verify: --budget needs PK_JOB_START (epoch seconds, set by the job\'s first step)'); return 2; }
        const note = budgetNote(`${JOBS[opts.budget].name} job`, Date.now() / 1000 - t0, JOBS[opts.budget].budget);
        console.log(note);
        if (note.includes('WARNING') && env.GITHUB_ACTIONS) console.log(`::warning title=time budget::${escapeAnnotation(note.split('\n')[1])}`);
        if (env.GITHUB_STEP_SUMMARY) fs.appendFileSync(env.GITHUB_STEP_SUMMARY, `${note}\n\n`);
        return 0;
    }

    const selected = selectChecks(opts);
    const base = resolveBase({ opts, env });
    const dirtyBefore = git(['status', '--porcelain', '--untracked-files=no']).stdout.split('\n').filter(Boolean);
    const ctx = { root, base, dirtyBefore };
    const ci = Boolean(env.GITHUB_ACTIONS);
    const t0 = performance.now();
    console.log(`verify: ${selected.map(c => c.id).join(', ')}${base ? ` (base ${base})` : ''}`);
    const results = await runChecks(selected, ctx, (check, r) => console.log(formatResult(check, r, { verbose: opts.verbose, ci })));
    const total = performance.now() - t0;
    const count = s => results.filter(r => r.status === s).length;
    console.log(`\nverify: ${count('ok')} ok, ${count('FAIL')} failed, ${count('skip')} skipped in ${seconds(total)}`);
    const label = opts.only.length ? `verify --only ${opts.only.join(',')}` : opts.fast ? 'verify --fast' : 'verify';
    writeCiFiles(results, total, label, env);
    if (count('FAIL')) {
        console.log(`Reproduce one check: node scripts/verify.mjs --only ${results.find(r => r.status === 'FAIL').check.id}`);
        return 1;
    }
    return 0;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) process.exit(await main(process.argv.slice(2)));
