// GENERATED by tools/build.mjs from elements/context-menu/: do not edit.
import { PkElement, define } from '../../js/element.js';
import { place, onOutside, unplace } from '../../js/positioning.js';
import { moveFocus } from '../../js/menu-logic.js';

const rows = el => el.slotted('menu').filter(i => i.localName === 'pk-menu-item' && !i.disabled && !['header', 'divider'].includes(i.type));
const behaviour = Base => class extends Base {
    connected() { this.setup(); if (this.open && !this.$o) this.arm(); }
    arm() { this.$o = onOutside([this], e => this.request(e.type === 'keydown' ? 'escape' : 'outside')); }
    setup() {
        if (!this.$w) {
            this.$w = true; this.$s = { buffer: '', at: 0 };
            this.addEventListener('contextmenu', e => { if (this.disabled || e.target.closest('[slot="menu"]')) return; e.preventDefault(); this.showAt(e.clientX, e.clientY, false); });
            this.addEventListener('keydown', e => {
                if (this.open) { if (e.key === 'Tab') this.request('tab'); else moveFocus(e, rows(this), this.$s); return; }
                if (!this.disabled && ((e.key === 'F10' && e.shiftKey) || e.key === 'ContextMenu')) { e.preventDefault(); const r = e.target.getBoundingClientRect(); this.showAt(r.left, r.bottom, true); }
            });
            this.addEventListener('pointerdown', e => { if (e.pointerType === 'touch' && !this.disabled) this.$t = setTimeout(() => { this.$swallow = true; this.showAt(e.clientX, e.clientY, false); }, 500); });
            for (const t of ['pointerup', 'pointercancel', 'pointermove']) this.addEventListener(t, () => clearTimeout(this.$t));
            this.addEventListener('pk-select', () => this.open && this.request('select'));
        }
    }
    disconnected() { this.stop(); clearTimeout(this.$t); }
    changed(name) { if (name === 'open' && !this.open) { this.stop(); unplace(this.part('menu')); } }
    hide() { this.open = false; }
    showAt(x, y, focusFirst) {
        this.open = true;
        const menu = this.part('menu');
        place({ x, y }, menu, { placement: 'bottom-start', offset: 0 });
        this.stop();
        this.arm();
        if (focusFirst) rows(this)[0]?.focus({ preventScroll: true });
        this.emit('pk-open', { x, y });
    }
    request(reason) { if (this.emit('pk-close', { reason })) this.open = false; }
    stop() { this.$o?.(); this.$o = null; }
};
export default define(class extends behaviour(PkElement) {
    static tag = "pk-context-menu";
    static props = {"open":{"type":"boolean","default":false,"reflect":true},"disabled":{"type":"boolean","default":false,"reflect":true}};
    static delegatesFocus = false;
    static formAssociated = false;
    static template = "<slot></slot><div part=\"menu\" role=\"menu\"><slot name=\"menu\"></slot></div>";
    static css = "/* pk-context-menu: the region is the host; the menu is a fixed layer at the pointer. Same look as the dropdown menu. */\n:host { display: block; }\n\n[part=\"menu\"] {\n    display: none;\n    position: fixed;\n    top: 0;\n    left: 0;\n    z-index: var(--z-pop);\n    box-sizing: border-box;\n    min-width: 12rem;\n    max-width: calc(100vw - 2 * var(--space-4));\n    max-height: min(24rem, calc(100dvh - 2 * var(--space-4)));\n    overflow-y: auto;\n    overscroll-behavior: contain;\n    padding: var(--space-1);\n    background: var(--color-panel);\n    color: var(--color-text);\n    border: 1px solid var(--color-border);\n    border-radius: var(--radius-md);\n    box-shadow: var(--shadow-pop);\n}\n\n:host([open]) [part=\"menu\"] { display: block; }\n";
});
