// GENERATED by tools/build.mjs from elements/stack/: do not edit.
import { PkElement, define } from '../../js/element.js';
const behaviour = Base => Base;
export default define(class extends behaviour(PkElement) {
    static tag = "pk-stack";
    static props = {"gap":{"type":"enum","default":"md","values":["none","xs","sm","md","lg","xl"],"reflect":true},"align":{"type":"enum","default":"stretch","values":["stretch","start","center","end"],"reflect":true},"dividers":{"type":"boolean","default":false,"reflect":true}};
    static delegatesFocus = false;
    static formAssociated = false;
    static template = "<slot></slot>";
    static css = ":host { --_g: var(--space-4); display: flex; flex-direction: column; align-items: stretch; gap: var(--pk-stack-gap, var(--_g)); }\n:host([hidden]) { display: none; }\n:host([gap=\"none\"]) { --_g: 0px; }\n:host([gap=\"xs\"]) { --_g: var(--space-1); }\n:host([gap=\"sm\"]) { --_g: var(--space-2); }\n:host([gap=\"lg\"]) { --_g: var(--space-6); }\n:host([gap=\"xl\"]) { --_g: var(--space-8); }\n:host([align=\"start\"]) { align-items: flex-start; }\n:host([align=\"center\"]) { align-items: center; }\n:host([align=\"end\"]) { align-items: flex-end; }\n:host([dividers]) ::slotted(:not(:first-child)) { border-block-start: 1px solid var(--pk-stack-divider, var(--color-border)); padding-block-start: var(--pk-stack-gap, var(--_g)); }\n";
});
