// GENERATED by tools/build.mjs from elements/toast-stack/: do not edit.
import { PkElement, define } from '../../js/element.js';
const POSITIONS = ['top-start', 'top', 'top-end', 'bottom-start', 'bottom', 'bottom-end'];

function show(message, o = {}) {
    const position = POSITIONS.includes(o.position) ? o.position : 'bottom-end';
    let stack = document.querySelector(`pk-toast-stack[position="${position}"]`);
    if (!stack) { stack = document.createElement('pk-toast-stack'); stack.setAttribute('position', position); document.body.append(stack); }
    const t = document.createElement('pk-toast');
    t.setAttribute('kind', o.kind ?? 'info');
    if (o.heading) t.heading = o.heading;
    if (Number.isFinite(o.duration)) t.duration = o.duration;
    if (o.noClose) t.noClose = true;
    t.append(document.createTextNode(message));
    if (o.action?.label) {
        const b = document.createElement('pk-button'); b.slot = 'action'; b.setAttribute('variant', 'ghost'); b.textContent = o.action.label;
        b.addEventListener('click', () => o.action.onClick?.());
        t.append(b);
    }
    stack.push(t);
    return t;
}

const behaviour = Base => class extends Base {
    static show(message, options) { return show(message, options); }
    connected() {
        if (!this.$w) {
            this.$w = true;
            this.watchSlot('', () => this.layout());
            this.addEventListener('pk-dismiss', () => queueMicrotask(() => this.layout()));
        }
        this.aria({ role: 'region', ariaLabel: 'Notifications' });
        globalThis.PkToast ??= this.constructor;
        this.layout();
    }
    changed(name) { if (name === 'max') this.layout(); }
    push(toast) { this.append(toast); }
    layout() {
        const toasts = this.slotted().filter(t => t.localName === 'pk-toast');
        toasts.forEach((t, i) => { const on = i < (this.max > 0 ? this.max : 3); t.hidden = !on; if (on) t.begin?.(); });
    }
};
export default define(class extends behaviour(PkElement) {
    static tag = "pk-toast-stack";
    static props = {"position":{"type":"enum","default":"bottom-end","values":["top-start","top","top-end","bottom-start","bottom","bottom-end"],"reflect":true},"max":{"type":"number","default":3,"reflect":true}};
    static delegatesFocus = false;
    static formAssociated = false;
    static template = "<slot></slot>";
    static css = "/* pk-toast-stack: a fixed column at one screen position. It lets clicks through except on the toasts themselves. */\n:host {\n    position: fixed;\n    z-index: var(--z-toast);\n    display: flex;\n    flex-direction: column;\n    gap: var(--space-2);\n    box-sizing: border-box;\n    width: var(--toast-w);\n    max-width: 100%;\n    padding: var(--space-4);\n    pointer-events: none;\n    inset-inline-end: 0;\n    inset-block-end: 0;\n    padding-bottom: max(var(--space-4), env(safe-area-inset-bottom));\n    padding-inline-end: max(var(--space-4), env(safe-area-inset-right));\n}\n\n::slotted(*) { pointer-events: auto; }\n\n:host([position^=\"top\"]) { inset-block: 0 auto; flex-direction: column-reverse; padding-top: max(var(--space-4), env(safe-area-inset-top)); padding-bottom: var(--space-4); }\n\n:host([position$=\"start\"]) { inset-inline: 0 auto; padding-inline: max(var(--space-4), env(safe-area-inset-left)) var(--space-4); }\n\n:host([position=\"top\"]), :host([position=\"bottom\"]) { inset-inline: 0; margin-inline: auto; }\n\n@media (max-width: 640px) {\n    :host, :host([position$=\"start\"]), :host([position=\"top\"]), :host([position=\"bottom\"]) { inset-inline: 0; width: 100%; margin-inline: 0; padding-inline: max(var(--space-4), env(safe-area-inset-left)) max(var(--space-4), env(safe-area-inset-right)); }\n}\n";
});
