// site/scorecard/api.current.json is generated by the build (the scorecard's API section diffs it against the baseline): it must match the sources.
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { build } from '../tools/build.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

test('api.current.json is what the build produces from the sources (run node tools/build.mjs when it fails)', () => {
    const { out } = build({ write: false });
    const built = out.get('site/scorecard/api.current.json');
    assert.ok(built, 'the build does not write api.current.json');
    const disk = fs.readFileSync(path.join(root, 'site', 'scorecard', 'api.current.json'), 'utf8').replace(/\r\n/g, '\n');
    assert.equal(disk, built.replace(/\r\n/g, '\n'));
});
