// site/scorecard/api.current.json is generated by the build (the scorecard's API section diffs it against the tracked release baseline): the build is
// deterministic and the file on disk (from node scripts/bootstrap.mjs) matches the sources.
import './needs-bootstrap.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { build } from '../tools/build.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

test('api.current.json is what the build produces from the sources, twice over (run node scripts/bootstrap.mjs when it fails)', () => {
    const built = build({ write: false }).out.get('site/scorecard/api.current.json');
    assert.ok(built, 'the build does not write api.current.json');
    assert.equal(build({ write: false }).out.get('site/scorecard/api.current.json'), built, 'the API surface is not deterministic');
    const disk = fs.readFileSync(path.join(root, 'site', 'scorecard', 'api.current.json'), 'utf8').replace(/\r\n/g, '\n');
    assert.equal(disk, built.replace(/\r\n/g, '\n'));
});
