// GENERATED by tools/build.mjs from elements/pager/: do not edit.
import { PkElement, define } from '../../js/element.js';
const behaviour = Base => Base;
export default define(class extends behaviour(PkElement) {
    static tag = "pk-pager";
    static props = {"label":{"type":"string","default":"Page navigation","reflect":true}};
    static delegatesFocus = false;
    static formAssociated = false;
    static template = "<nav part=\"nav\" aria-label=\"{{label}}\"><span part=\"prev\"><slot name=\"prev\"></slot></span><span part=\"note\"><slot></slot></span><span part=\"next\"><slot name=\"next\"></slot></span></nav>";
    static css = "/* pk-pager: previous on the start side, next on the end, an optional note between; stacks on a phone with the links full width. */\n:host { display: block; margin-block: var(--gap-section) 0; font-size: var(--text-read); }\n\n[part=\"nav\"] { display: grid; grid-template-columns: 1fr auto 1fr; align-items: center; gap: var(--space-3); }\n\n[part=\"next\"] { justify-self: end; text-align: end; }\n\n[part=\"note\"] { color: var(--color-muted); font-size: var(--text-meta); }\n\n::slotted(a) { display: inline-flex; align-items: center; min-height: var(--touch-target); padding: var(--space-2) var(--space-4); border: 1px solid var(--color-border); border-radius: var(--radius-md); color: var(--color-link); text-decoration: none; }\n\n::slotted(a:hover) { background: var(--color-surface-alt); border-color: var(--color-accent); }\n\n::slotted(a:focus-visible) { outline: var(--focus-ring); outline-offset: 2px; }\n\n@media (max-width: 640px) {\n    [part=\"nav\"] { grid-template-columns: 1fr; }\n    [part=\"next\"], [part=\"prev\"] { justify-self: stretch; }\n    ::slotted(a) { display: flex; justify-content: center; }\n    [part=\"note\"] { order: -1; text-align: center; }\n}\n";
});
