// GENERATED by tools/build.mjs from elements/textarea/: do not edit.
import { PkElement, define } from '../../js/element.js';
export const flagsOf = v => { const o = {}; for (const k in v) o[k] = v[k]; return o; };
export const autogrowHeight = (scrollHeight, borderY, maxHeight = 0) => { const h = scrollHeight + borderY; return maxHeight > 0 ? Math.min(h, maxHeight) : h; };

const behaviour = Base => class extends Base {
    connected() {
        if (this.$init) return;
        this.$init = true; this.$initial = this.value;
        const t = this.part('control');
        t.addEventListener('input', () => { this.$typing = true; this.value = t.value; this.fit(); });
        t.addEventListener('change', () => { this.dispatchEvent(new Event('change', { bubbles: true, composed: true })); this.emit('pk-value-change', { value: this.value }); });
    }
    fit() {
        const t = this.part('control');
        if (!this.autogrow || CSS.supports('field-sizing', 'content')) return;
        t.style.height = 'auto';
        t.style.height = `${autogrowHeight(t.scrollHeight, t.offsetHeight - t.clientHeight, this.maxHeight)}px`;
    }
    updated() {
        const t = this.part('control');
        if (!this.$typing && t.value !== this.value) t.value = this.value;
        this.$typing = false;
        if (this.maxHeight > 0) this.style.setProperty('--pk-textarea-max-height', `${this.maxHeight}px`); else this.style.removeProperty('--pk-textarea-max-height');
        this.fit();
        this.setValidity(flagsOf(t.validity), t.validationMessage, t);
        this.setFormValue(this.value);
    }
    onReset() { this.value = this.$initial ?? ''; }
    onRestore(state) { this.value = state ?? ''; }
    focus(o) { this.part('control').focus(o); }
    select() { this.part('control').select(); }
};
export default define(class extends behaviour(PkElement) {
    static tag = "pk-textarea";
    static props = {"name":{"type":"string","default":"","reflect":true},"value":{"type":"string","default":"","reflect":false},"placeholder":{"type":"string","default":"","reflect":true},"label":{"type":"string","default":"","reflect":true},"description":{"type":"string","default":"","reflect":false},"disabled":{"type":"boolean","default":false,"reflect":true},"readonly":{"type":"boolean","default":false,"reflect":true},"required":{"type":"boolean","default":false,"reflect":true},"invalid":{"type":"boolean","default":false,"reflect":true},"warning":{"type":"boolean","default":false,"reflect":true},"valid":{"type":"boolean","default":false,"reflect":true},"rows":{"type":"number","default":3,"reflect":false},"minlength":{"type":"string","default":"","reflect":true},"maxlength":{"type":"string","default":"","reflect":true},"autogrow":{"type":"boolean","default":false,"reflect":true},"maxHeight":{"type":"number","default":0,"reflect":false}};
    static delegatesFocus = true;
    static formAssociated = true;
    static template = "<div part=\"box\" class=\"box\"><textarea part=\"control\" rows=\"{{rows}}\" placeholder=\"{{placeholder}}\" disabled=\"{{disabled}}\" readonly=\"{{readonly}}\" required=\"{{required}}\" minlength=\"{{minlength}}\" maxlength=\"{{maxlength}}\" aria-label=\"{{label}}\" aria-description=\"{{description}}\" aria-invalid=\"{{invalid|str}}\"></textarea></div>";
    static css = ":host { display: block; --_bd: var(--pk-control-border, var(--color-input-border)); }\n:host(:is([invalid], [aria-invalid=\"true\"])) { --_bd: var(--field-error); }\n:host([warning]) { --_bd: var(--field-warn); }\n:host([valid]) { --_bd: var(--field-ok); }\n.box { position: relative; display: flex; align-items: center; gap: var(--space-1); min-height: var(--ctl-h); padding-inline: var(--space-3); background: var(--pk-control-bg, var(--color-input)); border: 1px solid var(--_bd); border-radius: var(--pk-control-radius, var(--radius-sm)); transition: border-color 0.15s; }\n:host(:is([invalid], [aria-invalid=\"true\"])) .box, :host([warning]) .box, :host([valid]) .box { box-shadow: inset 0 0 0 1px var(--_bd); }\n:host(:not([disabled], [readonly])) .box:hover { border-color: var(--color-muted); }\n.box:focus-within { border-color: var(--color-accent-hover); outline: var(--focus-ring); outline-offset: 2px; }\n:host([disabled]) .box { opacity: 0.55; cursor: not-allowed; }\n:host([readonly]) .box { background: var(--color-surface-alt); }\n:host([size=\"sm\"]) .box { min-height: calc(var(--ctl-h) * 0.8); }\n:host([size=\"lg\"]) .box { min-height: calc(var(--ctl-h) * 1.2); padding-inline: var(--space-4); }\ninput, textarea, select { flex: 1; align-self: stretch; min-width: 0; padding: var(--space-2) 0; border: 0; outline: 0; background: transparent; color: var(--color-text); font: inherit; font-size: var(--text-read); line-height: 1.3; }\n::placeholder { color: var(--color-muted); opacity: 1; }\n@media (max-width: 640px) { .box { min-height: var(--touch-target); } input, textarea, select { font-size: 16px; } }\n.box { align-items: stretch; }\ntextarea { min-height: calc(var(--ctl-h) * 1.6); resize: vertical; }\n:host([autogrow]) textarea { min-height: var(--ctl-h); resize: none; field-sizing: content; max-height: var(--pk-textarea-max-height, none); }\n";
});
