// GENERATED by tools/build.mjs from elements/field-row/: do not edit.
import { PkElement, define } from '../../js/element.js';
const behaviour = Base => Base;
export default define(class extends behaviour(PkElement) {
    static tag = "pk-field-row";
    static props = {"align":{"type":"enum","default":"stretch","values":["stretch","end","center"],"reflect":true}};
    static delegatesFocus = false;
    static formAssociated = false;
    static template = "<slot></slot>";
    static css = ":host { display: flex; flex-wrap: wrap; gap: var(--pk-field-row-gap, var(--space-4)); margin-bottom: var(--pk-field-row-margin, var(--space-3)); }\n:host([hidden]) { display: none; }\n:host([align=\"end\"]) { align-items: flex-end; }\n:host([align=\"center\"]) { align-items: center; }\n::slotted(pk-field), ::slotted(.ff) { flex: 1 1 120px; min-width: 120px; }\n::slotted(.ff--wide) { flex: 1 1 100%; }\n::slotted(pk-checkbox), ::slotted(pk-switch) { flex: 0 0 auto; align-self: center; }\n";
});
